### ISSUE TITLE
no effect of changing batch size in the time it takes to generate embeddings.

### ISSUE THREAD

**Issue by avikpal00** [facebookresearch/DPR#100]
Hello,
I am trying to generate embeddings from a large text corpus (22gb). To run the generate_dense_embeddings.py script I am using this command:

python generate_dense_embeddings.py --model_file=checkpoint/retriever/single/nq/bert-base-encoder.cp --ctx_file=text_corpus.tsv --out_file=test_embedding --batch_size=128 --shard_id=0 --num_shards=1000

The problem is it takes the same amount of time to complete with different batch sizes. I have tried with batch sizes - 1, 32, 64, 128, 256, 512, 1024. Time taken for this to complete is always similar (~18 minutes). GPU storage utilization increases on increasing batch size but processing speed is still same.

Need help with this and please tell if I am missing something in the command. I would really like it to process faster since I'm working with a large file.

Thanks in advance.

**Comment by vlad-karpukhin** [comment]
Hi @avikpal00 ,
Your script params seems to be fine.
How many passages do you have in your text_corpus.tsv ?
I see you have a lot of shards. Also, it seems strange you can ran such large batches like 512 or 1024. What is your hardware configuration ?

**Comment by avikpal00** [comment]
Thanks for the reply,
My corpus has ~22 million passages. I have kept shard count at 1000 to test against only a small fraction of the dataset and get an approximate of how much time it would take to index the corpus on a single gpu.
Since, it seemed to take same amount of time for lower batch sizes (1, 32, 64, 128 256), I tried with larger sizes (512, 1024) and found it still took the same time.
I am using a gcloud instance with 1x NVIDIA Tesla T4 and 8 vCPUs, 54 GB memory.

**Comment by vlad-karpukhin** [comment]
Hi @avikpal00,

I'll try to experiment with different batch sizes but as I remember,  it should affect the script running time.

My only guess now is that part of the processing time (about 10 minutes) is spent on data reading and model preparation before the model starts generating embeddings. Given your small shard size, it may be that the ratio of time spent on  actual generation is relatively small so you don't see the effect of an increased batch size?

**Comment by vlad-karpukhin** [comment]
UPD:
 Tried 128 & 256 batch sizes on 2 gpus. ~700k passages
bsz=128: run time 53 min
bsz=256: run time 54 min
 
 Indeed, there is almost no difference in processing times.
 
 Since this is just a forward pass through a BERT encoder, this is hardly what DPR can improve on. 
 
 My guess is that data processing(iteration, tokenization, creating batch tensors, exchanging tensors between gpu and ram) takes more time than the actual GPU based forward passes.
 
 But it is still really strange that you got same processing time for bsz=1 and were able to set 1024 as batch size
