### ISSUE TITLE
How to proceed when documents have no title for retrieval using DPR?

### ISSUE THREAD

**Issue by NThakur20** [facebookresearch/DPR#103]
Hello, 

I had a small doubt regarding retrieval using the DPR context encoder. I wish to retrieve documents on a dataset with no titles present. Should I pass the titles argument in DPRContextEncoderTokenizer as an empty list, or would it be advisable to pass the text (context) in the title feild as well?

Kind Regards,
Nandan

**Comment by vlad-karpukhin** [comment]
Hi @NThakur20 ,
I can only advice to somehow make titles or their equivalents. DPR was trained using titles and benefits from it.
If should work if you don't provide them (i.e. it should not crash), but the model quality will most likely drop by a few points.
