### ISSUE TITLE
imbalanced GPU memory usage

### ISSUE THREAD

**Issue by wasiahmad** [facebookresearch/DPR#104]
During DPR training, memory usage in GPU:0 becomes higher comparing to other GPUs. It is probably because the question and context vectors are gathered in GPU:0 to calculate the loss. Is there any way, we can modify the computation such that the GPU usage becomes balanced?

**Comment by vlad-karpukhin** [comment]
Hello,
Both question & context encoders are located at all gpus.
DDP mode should have more or less same gpu memory consumption.
DP mode might have it skewed.
Which one do you use?

**Comment by vlad-karpukhin** [comment]
guess this can be closed now without further details provided
