### ISSUE TITLE
(Question) using transformers other that bert

### ISSUE THREAD

**Issue by ali-abz** [facebookresearch/DPR#105]
Hi,
This is such a great tool and I would like to know if it is possible to use other transformers instead of bert (for non-english retrieval).
As far as I understand, DPR is presented with 3 models and that's it. Can I modify hf_model.py and replace bert with something else?

**Comment by vlad-karpukhin** [comment]
Hi @ali-abz ,
You can sure modify our models module and create you own encoder - have a look at how we initialize models via models/init.py.

**Comment by ali-abz** [comment]
Thanks.
