### ISSUE TITLE
How to speed up the batch creating operation?

### ISSUE THREAD

**Issue by SparkJiao** [facebookresearch/DPR#113]
Hi, thanks for your contribution.

I found that the GPU usage is low and I think this is because the `create_biencoder_input` and `_calc_loss` methods cost much time, since the two need iterate the samples in a batch for subsequent processing,

I wanna re-construct it through multiprocessing, like that in `DataLoader`. Is it possible? Do you have any suggestions?

Thanks for your help!

**Comment by vlad-karpukhin** [comment]
Hi @SparkJiao ,
 nvidia-smi shows about 70-100% gpu usage during training for me.
 Sure, you can speed things up by tokenizing all the text before training, serializing tensor batches, storing it somewhere and then reading all data in RAM, if its capacity allows.
 I'm not sure that multiprocessing can help here. There is a cost of thread/process scheduling & memory synchronization, and python is simply not good at it if you need low latency.
 _calc_loss operates on cuda based tensors, that also might pose some issues.

**Comment by SparkJiao** [comment]
Thanks for your detailed suggestions, I will try it later.

I'll close the issue, thank you very much!
