### ISSUE TITLE
Roberta performs worst than Bert?

### ISSUE THREAD

**Issue by yeliu918** [facebookresearch/DPR#115]
Hi,

I try the DPR Roberta-based with the same configuration as the BERT-based. Namely, max_grad_norm 2.0 --warmup_steps 1237 --batch_size 128 --do_lower_case --num_train_epochs 40 

I get the performance as below:
                        Top-1  |Top-5|Top-20|Top-100                      
Bert DPR        | 43.91 | 67.70 | 79.56 | 86.59
Roberta DPR  |42.27 | 66.18 | 77.56  | 85.51

How are your results on Roberta?
Based on my previous experiments on other tasks, I think Roberta always outperforms Bert. But this result doesn't. 
And why do you use the Fairseq rather than Huggingface Roberta? And the library of Fairseq fairseq_roberta.extract_features cannot take attention_mask as input. Do you think that's the reason why it gets worse performance?

**Comment by vlad-karpukhin** [comment]
Hi,
I didn't put a lot of effort trying to find a better hyperparameters setup for roberta. I've got the result similar to yours - roberta was slightly worse. I have no idea if this is because of non lucky hyperparams set or because of roberta's missing next sentence predictions pre-training for CLS token which we use in DPR.

I used faiseq roberta because of
- some internal FB needs 
- to have an integration example with another popular model library besides HF.

**Comment by yeliu918** [comment]
Hi @vlad-karpukhin,

Thanks for the quick response. Could you clarify the hyperparameters in DPR? I think they are [max_grad_norm, warmup_steps, batch_size] ? I can try and let you know the new result.

And I think Roberta contains CLS_token, which is <s>, so Roberta can still use CLS_token to represent the embedding. Roberta's missing next sentence predictions will lead to the type_token_ids missing. But I don't think you use the different type_token for title and passage in the passage encoder.

**Comment by vlad-karpukhin** [comment]
There are a bunch of other hyperparams
See conf/train/biencoder_nq.yaml config file.

As of the CLS token - Roberta's <s> is not the same as BERT's CLS but I used it successfully.
There should not be a problem with the current code - I use HF's tokenizer and it has the attribute sep_token_id which works for both BERT's & Roberta's bpe tokenizers.

**Comment by vlad-karpukhin** [comment]
guess this can be closed now
