### ISSUE TITLE
Reader Inference on Supplied Model, Retrieved Files

### ISSUE THREAD

**Issue by mosicr** [facebookresearch/DPR#117]
Hi, 
I am trying to run inference using supplied files:
python3 train_extractive_reader.py prediction_results_file=junk.out eval_top_docs=10 dev_files=/home/\
   ranko_mosic/DPR/dpr/downloads/data/retriever_results/nq/single-adv-hn/test.json model_file=/home/rank\
   o_mosic/DPR/dpr/downloads/checkpoint/retriever/single-adv-hn/nq/bert-base-encoder.cp train.dev_batch_\
   size=8  passages_per_question_predict=100 encoder.sequence_length=350

Files don't seem to be a match - I am getting:
340  File "train_extractive_reader.py", line 102, in __init__
341    self._load_saved_state(saved_state)
342  File "train_extractive_reader.py", line 434, in _load_saved_state
343    model_to_load.load_state_dict(saved_state.model_dict)
344  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1224, in load_state_\
   dict
345    self.__class__.__name__, "\n\t".join(error_msgs)))
346RuntimeError: Error(s) in loading state_dict for Reader:
347        Missing key(s) in state_dict: "encoder.embeddings.position_ids", "encoder.embeddings.word_emb\
   eddings.weight", "encoder.embeddings.position_embeddings.weight", "encoder.embeddings.token_type_embe\
   ddings.weight", "encoder.embeddings.LayerNorm.weight", "encoder.embeddings.LayerNorm.bias", "encoder.\
   encoder.layer.0.attention.self.query.weight", "encoder.encoder.layer.0.attention.self.query.bias", "e\
   ncoder.encoder.layer.0.attention.self.key.weight", "
.....
...
348        Unexpected key(s) in state_dict: "question_model.embeddings.word_embeddings.weight", "questio\
   n_model.embeddings.position_embeddings.weight", "question_model.embeddings.token_type_embeddings.weig\
   ht", "question_model.embeddings.LayerNorm.weight", "question_model.embeddings.LayerNorm.bias", "quest\
   ion_model.encoder.layer.0.attention.self.query.weight", "question_model.encoder.layer.0.attention.sel\
   f.query.bias", "question_model.encoder.layer.0.attention.self.key.weight", "question_model.encoder.la\
   yer.0.attention.self.key.bias", "question_model.encoder.layer.0.attention.self.value.weight", "questi

**Comment by vlad-karpukhin** [comment]
Hi @mosicr ,
Looks like you are using a retriever checkpoint  (/home/rank
o_mosic/DPR/dpr/downloads/checkpoint/retriever/single-adv-hn/nq/bert-base-encoder.cp) as the reader model.
The reader model is different from the retriever and one should use reader checkpoints (like 'checkpoint.reader.nq-single.hf-bert-base') when running reader evaluation with train_extractive_reader.py.

Also, we don't provide the reader checkpoint trained on the new retriever results (but you can still evaluate the old reader).

**Comment by mosicr** [comment]
Great, thank you very much Vlad, it is working now !!
