### ISSUE TITLE
Positive contexts

### ISSUE THREAD

**Issue by hnt4499** [facebookresearch/DPR#118]
Hi, thanks for the amazing paper and code.

I have several questions regarding the positive contexts:
1. I observe that for each question, there are multiple positive passages in `nq-train.json`, and some of them seem incorrect. Are those considered positive just because they contain the answer string? Are they being used for training? What are the "score" and "title_score"?
2. Same questions for `nq-adv-hn-train.json`. However, for this dataset, it seems like all positive passages are correct. How is this retrieved differently from `nq-train.json`?

Thank you!

**Comment by vlad-karpukhin** [comment]
Hi  @hnt4499 ,
1. The only semi-supervised way to tell if a passage is positive or not is to check the answer aspen presence. That is what we did. Sure, it sometimes leads to false positives (as well as false negatives selected for hard negatives). Those positives are not used for training unless you explicitly force them to be used. We have an ablation experiment in our paper - as you can find, replacing gold positives with their semi-supervised versions is just slightly worse than the baseline. "Score" and "Title score" are bm25 scores which are present in the file but are not used in the current trianing.

2. The difference between them is that hard negatives were mined using BM25 in nq-train.json but using original DPR model & index in nq-adv-hn-train.json.

**Comment by hnt4499** [comment]
Hi @vlad-karpukhin 

Thank you for your clarification. How about the difference of **positive** passages between `nq-train.json` and `nq-adv-hn-train.json`? (since for the latter it seems more "correct")

**Comment by vlad-karpukhin** [comment]
Same applies for positive passages - they were mined using bm25 and DPR original model respectively.
Though I haven't tried to use them instead of the gold positives only (default setting).

**Comment by hnt4499** [comment]
Just to clarify, for the new model, you only used hard negatives mined from the original DPR model, but not the positive mined from it, is this correct?
And when both positives and negatives were mined from DPR, how do you distinguish them? (i.e., when a passage is in top-k retrieved from DPR, how can you tell it's a positive and not a negative). 
Thank you!

**Comment by vlad-karpukhin** [comment]
The data files contains both positives and hard negatives mined using the previous NQ dense index.
Since NQ has gold positives and we had an ablation study in the paper which showed that using them is still a little bit more preferable than using semi-supervised positives, I didn't use new positives in the new model but again used gold positives as before.
"And when both positives and negatives were mined from DPR, how do you distinguish them" - by checking the presence of any of the question's answers.

**Comment by hnt4499** [comment]
Thank you for the clarification!
