### ISSUE TITLE
Reader Inference Failing

### ISSUE THREAD

**Issue by mosicr** [facebookresearch/DPR#119]
Hi Vlad, 
I am trying to run reader inference via:
python3 train_extractive_reader.py prediction_results_file=junk.out eval_top_docs=3 dev_files=/home/ranko_mosic/DPR\
 /dpr/downloads/data/retriever_results/nq/single-adv-hn/test1.json model_file=/home/ranko_mosic/DPR/dpr/downloads/ch\
 eckpoint/retriever/single-adv-hn/nq/bert-base-encoder.cp train.dev_batch_size=8  passages_per_question_predict=5 en\
 coder.sequence_length=350

It fails with:
python3 train_extractive_reader.py prediction_results_file=junk.out eval_top_docs=3 dev_files=/home/ranko_mosic/DPR\
 /dpr/downloads/data/retriever_results/nq/single-adv-hn/test1.json model_file=/home/ranko_mosic/DPR/dpr/downloads/ch\
 eckpoint/retriever/single-adv-hn/nq/bert-base-encoder.cp train.dev_batch_size=8  passages_per_question_predict=5 en\
 coder.sequence_length=350

Also, DPR post references train_reader.py file which does not exist ( I am using train_extractive_reader.py instead ):
_In order to make an inference, **run train_reader.py** without specifying train_files. Make sure to specify model_file with the path to the checkpoint_

**Comment by vlad-karpukhin** [comment]
Hi @mosicr ,

It seems you forgot to provide an error message.
Also, you are trying to use retriever checkpoint with as the reader (Your model_file's name suggests it is the retriever). That is probably the reason.

**Comment by mosicr** [comment]
Hi Vlad, 
Apologies for confusion. I am now trying reader inference with reader checkpoint:
python3 train_extractive_reader.py prediction_results_file=junk.out eval_top_docs=3 dev_files=/home/ranko_mosic/DPR\
 /dpr/downloads/data/retriever_results/nq/single-adv-hn/test1.json model_file=/home/ranko_mosic/DPR/dpr/downloads/ch\
 eckpoint/reader/nq-single/hf-bert-base.cp train.dev_batch_size=8  passages_per_question_predict=5 encoder.sequence_\
 length=350 
It fails with:
860[2021-03-26 11:23:58,649][root][INFO] - Loading checkpoint @ batch=1736 and epoch=18
861[2021-03-26 11:23:58,650][root][INFO] - Loading model weights from saved state ...
862Traceback (most recent call last):
863  File "train_extractive_reader.py", line 603, in main
864    trainer = ReaderTrainer(cfg)
865  File "train_extractive_reader.py", line 102, in __init__
866    self._load_saved_state(saved_state)
867  File "train_extractive_reader.py", line 434, in _load_saved_state
868    model_to_load.load_state_dict(saved_state.model_dict)
869  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
870    self.__class__.__name__, "\n\t".join(error_msgs)))
871RuntimeError: Error(s) in loading state_dict for Reader:
872        Missing key(s) in state_dict: "encoder.embeddings.position_ids".

In order to cut on machine resource requirements I am using very small retriever results file.

**Comment by vlad-karpukhin** [comment]
eval_top_docs is supposed to be a list of top-k thresholds

Can you replace 
eval_top_docs=3 
with
eval_top_docs=[3]

**Comment by mosicr** [comment]
It is working now, thank you Vlad for timely response !! 
Have a great weekend !!
