### ISSUE TITLE
Embedding File Request

### ISSUE THREAD

**Issue by feipenghe** [facebookresearch/DPR#120]
Any embedding generated for latest wikipedia passages psgs_w100_20200201.tsv?

**Comment by vlad-karpukhin** [comment]
Hi @feipenghe ,
Sorry, what is the latest wikipedia passages?
We don't update wikipedia in DPR as of now. For example, NQ dataset is designed from a specific wikipedia snapshot and has  a lot of time sensitive questions which now should have different answers.

**Comment by feipenghe** [comment]
I see. Thanks for the comment!
