### ISSUE TITLE
Retriever Inference Failing

### ISSUE THREAD

**Issue by mosicr** [facebookresearch/DPR#121]
Hi Vlad, 
Ever so small failure again :-) : 
python3 generate_dense_embeddings.py model_file=/home/ranko_mosic/DPR/dpr/downloads/checkpoint/retriever/single/nq/\
 bert-base-encoder.cp ctx_src=/home/ranko_mosic/DPR/dpr/downloads/data/retriever/nq-dev.json shard_id=0 num_shards=5\
 0 out_file=/home/ranko_mosic/DPR/retriever_inf

Fails with:
344[2021-03-28 14:53:38,386][root][INFO] - Loading saved model state ...
345[2021-03-28 14:53:38,440][root][INFO] - reading data source: /home/ranko_mosic/DPR/dpr/downloads/data/retriever/n\
   q-dev.json
346Traceback (most recent call last):
347  File "generate_dense_embeddings.py", line 173, in <module>
348    main()
349  File "/usr/local/lib/python3.7/dist-packages/hydra/main.py", line 37, in decorated_main
350    strict=strict,
351  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 347, in _run_hydra
352    lambda: hydra.run(
353  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 201, in run_and_report
354    raise ex
355  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 198, in run_and_report
356    return func()
357  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 350, in <lambda>
358    overrides=args.overrides,
359  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/hydra.py", line 112, in run
360    configure_logging=with_log_configuration,
361  File "/usr/local/lib/python3.7/dist-packages/hydra/core/utils.py", line 127, in run_job
362    ret.return_value = task_function(task_cfg)
363  File "generate_dense_embeddings.py", line 144, in main
364    ctx_src = hydra.utils.instantiate(cfg.ctx_sources[cfg.ctx_src])
365  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 318, in __getitem__
366    key=key, value=None, cause=e, type_override=ConfigKeyError
367  File "/usr/local/lib/python3.7/dist-packages/omegaconf/base.py", line 101, in _format_and_raise
368    type_override=type_override,
369  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 629, in format_and_raise
370    _raise(ex, cause)
371  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 610, in _raise
372    raise ex  # set end OC_CAUSE=1 for full backtrace
373omegaconf.errors.ConfigKeyError: Key '/home/ranko_mosic/DPR/dpr/downloads/data/retriever/nq-dev.json' is not in s\
   truct
374        full_key: ctx_sources./home/ranko_mosic/DPR/dpr/downloads/data/retriever/nq-dev.json
375        reference_type=Optional[Dict[Union[str, Enum], Any]]
376        object_type=dictd

I added strict=False to generate_dense_embeddings.py 
140    model_to_load.load_state_dict(ctx_state, strict=False)

**Comment by feipenghe** [comment]
What I did is to set argument ctx_src=dpr_wiki to use the default wikipedia file. It's a configuration file located [here](https://github.com/facebookresearch/DPR/blob/master/conf/ctx_sources/default_sources.yaml). You might need to make change based on that if you want to train on some other files.

**Comment by vlad-karpukhin** [comment]
Hi @mosicr , 
as @feipenghe correctly noted, you now need to define all input data components in the configuration along with code components to read&parse them and then use their config name. This is how things have changed in DPR with the new release. One can't just set file name for the data, though this might be a good default behavior with the default data loader class.
As of now, please just follow configuration instructions which in your case means just replacing file path with the dataset resource name.

**Comment by mosicr** [comment]
Thank you @feipenghe and Vlad.

**Comment by mosicr** [comment]
If we want to use our own file as input, is it required to upload it to a cloud ?

**Comment by vlad-karpukhin** [comment]
No it is not needed for sure. You can just put your file path as 'file:' attribute for your datasets in the configuration file. 
The current logic is to first check of the 'file' attribute is an existing filesystem path and only if not, try to use it as the downloadable aws resource name.

**Comment by mosicr** [comment]
Great, it is working. Much appreciated !!
