### ISSUE TITLE
CPU Only Inference

### ISSUE THREAD

**Issue by mosicr** [facebookresearch/DPR#122]
Hi, 
Is it possible to run inference on CPU only ? 
I am trying to run on a GCP free trial, no GPU instance:
python3 dense_retriever.py model_file=/home/ranko_mosic/DPR/dpr/downloads/checkpoint/retriever/single/nq/bert-base-\
 encoder.cp qa_dataset=nq_test ctx_datatsets=[dpr_wiki] encoded_ctx_files=[\"/home/ranko_mosic/DPR/retriever_inf\"] \
 out_file=retr_inf.out

It fails with:
648Traceback (most recent call last):
649  File "dense_retriever.py", line 356, in main
650    questions, query_token=qa_src.special_query_token
651  File "dense_retriever.py", line 127, in generate_question_vectors
652    selector=self.selector,
653  File "dense_retriever.py", line 78, in generate_question_vectors
654    q_ids_batch = torch.stack(batch_token_tensors, dim=0).cuda()
655  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 170, in _lazy_init
656    torch._C._cuda_init()
657RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a dri\
   ver from http://www.nvidia.com/Download/index.aspx
658

I did set no_cuda: True  in dense_retriever.yaml 

Regards, Ranko

**Comment by hnt4499** [comment]
The error, as seen from the traceback, arised from line [#78 ](https://github.com/facebookresearch/DPR/blob/5e26786b43eb19a517ac6ca01291a6a22614dbc3/dense_retriever.py#L78)and [#79](https://github.com/facebookresearch/DPR/blob/5e26786b43eb19a517ac6ca01291a6a22614dbc3/dense_retriever.py#L79). A workaround would be to remove `.cuda()`  from those two lines. You need to re-add `.cuda()` if you want to use GPU later.

**Comment by mosicr** [comment]
It is working !! Thank you very much, hht4499. Should've done it myself, I guess. 
Much appreciated !!
