### ISSUE TITLE
Reader Train - GPU out of Memory

### ISSUE THREAD

**Issue by robinsongh381** [facebookresearch/DPR#125]
Hello !

I was training a Reader model for NQ dataset with "suggested" hyper-parameters. (as suggested [here](https://github.com/facebookresearch/DPR/tree/sewon#5-reader-training))

```bash
python -m torch.distributed.launch \
	--nproc_per_node=8 train_reader.py \
	--seed 42 \
	--learning_rate 1e-5 \
	--eval_step 2000 \
	--do_lower_case \
	--eval_top_docs 50 \
	--encoder_model_type hf_bert \
	--pretrained_model_cfg bert-base-uncased \
	--train_file "./checkpoint/nq/reader_data/reader_train*" \
	--dev_file "./checkpoint/nq/reader_data/reader_dev*" \
	--warmup_steps 0 \
	--sequence_length 350 \
	--batch_size 16 \
	--passages_per_question 24 \
	--num_train_epochs 100000 \
	--dev_batch_size 72 \
	--passages_per_question_predict 50 \
	--output_dir {your save dir path}
```

The training was carried out on a single node of 8 GPUs each of which has 32GB memory. (Same as your setting)

However, I came across an out-of-memory error so i had to decrease `batch size`/ `passages_per_question` / `sequence_length`

```bash
python -m torch.distributed.launch \
	--nproc_per_node=8 train_reader.py \
	--seed 42 \
	--learning_rate 1e-5 \
	--eval_step 2000 \
	--do_lower_case \
	--eval_top_docs 50 \
	--encoder_model_type hf_bert \
	--pretrained_model_cfg bert-base-uncased \
	--train_file "./checkpoint/nq/reader_data/reader_train*" \
	--dev_file "./checkpoint/nq/reader_data/reader_dev*" \
	--warmup_steps 0 \
	--sequence_length 256 \
	--batch_size 16 \
	--passages_per_question 6 \
	--num_train_epochs 50 \
	--dev_batch_size 16 \
	--passages_per_question_predict 50 \
	--output_dir checkpoint/nq/m64_dense_e50/reader_ckpt_49 \
    --log_batch_step 100 \
```

This setting occupied about 29GB for all 8 GPUS

How did you mange to train with 8 GPUs with "suggested" hyper-parameters ?

**Comment by vlad-karpukhin** [comment]
unlike bi-encoder, we don't use DDP mode for the reader even though the code supports it.
So, can you just run it in DP mode by removing 'torch.distributed.launch' launcher?

Please refer to the 'reader training' section for example:
https://github.com/facebookresearch/DPR#5-reader-training

**Comment by robinsongh381** [comment]
Ok. Thank you Vlad !
