### ISSUE TITLE
Minor suggestion on the trivia-train.json

### ISSUE THREAD

**Issue by alexlimh** [facebookresearch/DPR#127]
Hi there,

I was finetuning the DPR model on the trivia dataset but found that there were many entries in trivia-train.json that contain no positive contexts. As the nq-train.json has no empty entries (cleaned up), I think it'd better clean up trivia as well for consistency purposes. Otherwise, it might lead to index mismatch if pre-trained query embeddings are used instead of the query encoder.

Best,

**Comment by vlad-karpukhin** [comment]
Hi @alexlimh ,

DPR can't create a sample without a single positive ctx per question. So all train samples without a single ctx+ are filtered out during training.

**Comment by alexlimh** [comment]
Hi @vlad-karpukhin,

I'm aware that the current DPR training script filters the empty entries. However, if people try to train models on trivia-train.json using their own codes, it might create problems (which happened in my case). Just saying that maybe we should probably let people aware of that.

**Comment by vlad-karpukhin** [comment]
ok, good point, thanks!

**Comment by alexlimh** [comment]
no problems :)

**Comment by vlad-karpukhin** [comment]
it is better to introduce this filtering regardless of data-loader class used, 
will try to move to some generic place in the training pipeline.

**Comment by alexlimh** [comment]
Right. For example in my case, I first use a pre-trained query encoder to encode all the queries in trivia-train.json and save the embeddings into a .pkl file which was later used in the training. The embeddings are not filtered so it creates a discrepancy. Therefore, instead of filtering all the derivatives of the empty training samples, I agree that the data cleaning should be moved to somewhere more generic.

**Comment by alexlimh** [comment]
BTW, the nq-train.json filters all the empty entries; I don't know why trivia still keeps them.

**Comment by vlad-karpukhin** [comment]
We just moved filtering to the train time code after initial experiments with NQ(already cleaned).

**Comment by yeliu918** [comment]
Hi,

May I ask do you use the same Wikipedia for NQ, TriviaQA, and SQuAD? The one in the download/data. 

Best,

**Comment by alexlimh** [comment]
yep, I did. But I was using the previous version of DPR for training 
 https://github.com/facebookresearch/DPR/tree/42161470d6f16d20c20f6ea2516941c224fc0b89

**Comment by yeliu918** [comment]
Thanks for your response. Have you tried SQuAD? I thought SQuAD needs the earlier Wikipedia dump, like 2016.  @vlad-karpukhin

**Comment by vlad-karpukhin** [comment]
Yes, we used the same wikipedia dump for all datasets.

**Comment by yeliu918** [comment]
I see, Thank you!
