### ISSUE TITLE
Question on Table 3

### ISSUE THREAD

**Issue by hnt4499** [facebookresearch/DPR#128]
Hi there,

Table 3 in the paper shows that the performances using gold passages as the only negatives differ significantly between in-batch training and non in-batch training.
<img width="506" alt="Screenshot 2021-04-07 at 15 13 39" src="https://user-images.githubusercontent.com/45118728/113825723-e9a86700-97b3-11eb-8b55-b0f808b4ec84.png">

Why is this the case? I suppose the only difference between these two settings is that in-batch training is more memory-efficient. Please correct me if I am wrong.

Best

**Comment by vlad-karpukhin** [comment]
There is not any formal explanation (you can hardly find any for black-box like systems in deep learning).
My intuition is that it(in batch negatives) allows the model to move gradients in a more consistent direction.
In the naive case, negative passage representation is moved from question, while the positive passage is moved closer to the question vector.
In the case if IB - passage representations are moved both (except hard negatives) TO and FROM some relevant and non relevant counterparts.

**Comment by hnt4499** [comment]
Interesting insight. Thank you
