### ISSUE TITLE
Top-k Result for Trivia QA

### ISSUE THREAD

**Issue by robinsongh381** [facebookresearch/DPR#131]
hello !

On #78  you commented that 

`
TriviaQA, test set:
Single model:
0.531
0.615
0.659
0.685
0.704
0.716
0.729
0.739
0.747
0.754
0.759
0.763
0.767
0.772
0.775
0.778
0.782
0.784
0.786
0.788
0.79
0.793
0.795
0.797
0.799
0.802
0.803
0.805
0.807
0.808
0.809
0.811
0.811
0.813
0.814
0.815
0.816
0.817
0.818
0.819
0.82
0.821
0.822
0.822
0.823
0.824
0.825
0.825
0.826
0.827
0.828
0.829
0.829
0.83
0.83
0.831
0.832
0.832
0.832
0.833
0.833
0.834
0.834
0.835
0.835
0.835
0.836
0.836
0.837
0.838
0.838
0.838
0.839
0.839
0.839
0.84
0.841
0.841
0.842
0.842
0.843
0.843
0.843
0.843
0.844
0.844
0.844
0.844
0.844
0.845
0.846
0.846
0.846
0.846
0.846
0.847
0.847
0.848
0.848
0.848
`

However, this is consistent with the Table 2.

![image](https://user-images.githubusercontent.com/42966248/114553544-b3318700-9ca0-11eb-8624-45b9b5792d89.png)

From the Table 2, The top-20 / 100 for Trivia QA test set is 79.4 and 85.0, respectively but your above comment suggests that the top-20/100 is 78.8 and 84.8, respectively. 

Which one is correct ?

**Comment by vlad-karpukhin** [comment]
Both may be correct, the difference in 0.2-0.1 accuracy points is normal form run to run with different HF version or a different seed.
I tried to find the original results but I don't have them anymore. 
You can just train a trivia-only model and evaluate the results. I'm sure they will be more or less the same.
You will probably get ~ 0.5 better results like I did for NQ with the most recent version of HF (some code changes are needed though).
