### ISSUE TITLE
frustrated trying to test the new modification on colab

### ISSUE THREAD

**Issue by sadakmed** [facebookresearch/DPR#132]
I was using the first version, and it was really simple, 

```python
!python train_dense_encoder.py \
	--encoder_model_type hf_bert  \
	--pretrained_model_cfg  bert-base-cased \
	--train_file train.json \
	--dev_file test.json \
        --do_lower_case \
        --eval_per_epoch 1 \
    --num_train_epochs 100  \
    --batch_size 4 \
    --learning_rate 0.000001 \
    --warmup_steps 10 \
	--output_dir out
```

now with hydra I can't just launch the training, 

```python
!git clone https://github.com/facebookresearch/DPR.gi
import os; os.chdir('DPR')
!pip install . 
!python train_dense_encoder.py \
            train_datasets=train.json\
            dev_datasets=test.json \
            train=biencoder_local \
            output_dir=.
```

Could you please provide a tutorial for that!

**Comment by vlad-karpukhin** [comment]
The readme has been updated on how to use hydra.
A separate instructions file has also been added https://github.com/facebookresearch/DPR/tree/master/conf
You need to specify the name of the dataset for both train_datasets & dev_datasets params (they should be lists now) as it is configured in the relevant configuration file.

I found the previous ArgParse-based tool configurations as a very limiting and making all follow-up projects quickly becoming configuration mess and simply not able to construct all the complex setups I needed.

Yes, using Hydra will require to learn it and how it is used on DPR but once that is done, it gives a lot of customization freedom and flexibility to modify this codebase for your needs.

As of the simplicity for the standard cases, I should probably make a backward compatibility when train/dev_datasets params were just pointing to specific files and use the old dataloader to handle them.

**Comment by sadakmed** [comment]
@vlad-karpukhin  correct me if I'm wrong,  I'm trying to train the retrieval part on my data, data follows the schema mentioned in readme (positive_ctxs, negative_ctxs and hard_negatives_ctxs ...)
and I made these changes:

in biencoder_train_cfg.yaml

```
defaults:
  - encoder: hf_bert
  - train: biencoder_default
  - datasets: encoder_train_default
```
in encoder_train_default.yaml

```
custom_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: train.json

custom_test:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: test.json

```


from terminal I entered the following command:

```
python DPR/train_dense_encoder.py \
    train_datasets=[custom_train]\
    dev_datasets=[custom_test] \
    train=biencoder_local \
    output_dir=ou
```

no error raised, but this log

> [2021-04-14 21:55:31,490][dpr.utils.conf_utils][INFO] - train_datasets: ['custom_train']
  [2021-04-14 21:55:31,510][dpr.data.biencoder_data][INFO] - Data files: []
  this is from config [<dpr.data.biencoder_data.JsonQADataset object at 0x7f550744d050>]
  [2021-04-14 21:55:31,510][dpr.utils.conf_utils][INFO] - dev_datasets: ['custom_test']
  [2021-04-14 21:55:31,527][dpr.data.biencoder_data][INFO] - Data files: []
  [2021-04-14 21:55:31,528][root][INFO] - Initializing task/set data ['custom_train']
  [2021-04-14 21:55:31,529][dpr.data.download_data][INFO] - no resources found for specified key
  [2021-04-14 21:55:31,529][dpr.data.biencoder_data][INFO] - Total cleaned data size: 0
  [2021-04-14 21:55:31,529][root][INFO] - samples_per_shard=0, shard_start_idx=0, shard_end_idx=0, max_iterations=0
  [2021-04-14 21:55:31,529][root][INFO] - rank=-1; Multi set data sizes [0]
  [2021-04-14 21:55:31,529][root][INFO] - rank=-1; Multi set total data 0
  [2021-04-14 21:55:31,529][root][INFO] - rank=-1; Multi set sampling_rates None
  [2021-04-14 21:55:31,529][root][INFO] - rank=-1; Multi set max_iterations per dataset [0]
  [2021-04-14 21:55:31,529][root][INFO] - rank=-1; Multi set max_iterations 0
  [2021-04-14 21:55:31,529][root][INFO] -   Total iterations per epoch=0
  [2021-04-14 21:55:31,530][root][WARNING] - No data found for training.

**Comment by vlad-karpukhin** [comment]
Hi @sadakmed ,
Looks like python can't find your train/test.json files. Can you try to put full fs path for those files in your config?

**Comment by iliemihai** [comment]
I've followed the hydra example, added train.json, test.json in conf/biencoder_train_cfg.yaml, but when I run `python3 train_dense_encoder.py +train_dataset="/work/playground/RAG/rag-end2end-retriever/KB_DATASET/train_dpr.json" +dev_dataset="/work/playground/RAG/rag-end2end-retriever/KB_DATASET/val_dpr.json" train=biencoder_local output_dir=output` I get the error `omegaconf.errors.ConfigKeyError: Key '/' is not in struct`.
Seems to be a bug in omegaconf at merging, but it s to confusing to debug

**Comment by sadakmed** [comment]
@iliemihai  try to use the full path, from the /**home**/*user_name*/*path_to_file*  -if u r on linux of course, if not just remove windows nd install linux-

**Comment by iliemihai** [comment]
@sadakmed thank you for the quick response. I am working on Linux. The path to the dataset is a full path, I am working in a mounted directory /work, so the full path is  `work/playground/RAG/rag-end2end-retriever/KB_DATASET/train_dpr.json` and `/work/playground/RAG/rag-end2end-retriever/KB_DATASET/val_dpr.json`
The biencoder_train_cfg.yaml file has the structure:
`
# configuration groups
defaults:
  - encoder: hf_bert
  - train: biencoder_default
  - datasets: encoder_train_default

train_datasets: /work/playground/RAG/rag-end2end-retriever/KB_DATASET/train_dpr.json
dev_datasets: /work/playground/RAG/rag-end2end-retriever/KB_DATASET/val_dpr.jsonoutput_dir: output
train_sampling_rates:
loss_scale_factors:
`

**Comment by vlad-karpukhin** [comment]
Hi @iliemihai ,
the train_datasets & dev_datasets params should be lists (from the Hydra configuration point of view), not single values.
I recommend to specify your datasets in https://github.com/facebookresearch/DPR/blob/master/conf/datasets/encoder_train_default.yaml
and then just use either command line parameter: train_datasets=[your ds config name]
or override it inside the 
biencoder_train_cfg.yaml fie
