### ISSUE TITLE
Additional data in the new NQ dataset

### ISSUE THREAD

**Issue by sbmaruf** [facebookresearch/DPR#137]
Hi! Just checked out your new implementation. Sleek improvement with hydra integration.

I see that you have added a new dataset `nq-adv-hn-train.json` (69639 samples) which contains slightly more data than the previous dataset `nq-train.json` (58880 samples). 

I was wondering where the improvements are coming from. Is it because of  10759 additional samples or the new hard negative data?

Also, the additional new data don't have any 1000 scored positive_ctxs passages. Is there any reason for that? Earlier I assumed that the highest scored passage contains the gold passage. Is that still valid for the new 10759 samples?

**Comment by vlad-karpukhin** [comment]
Hi,

Please see my answer for these two issues:

https://github.com/facebookresearch/DPR/issues/114
https://github.com/facebookresearch/DPR/issues/118

**Comment by sbmaruf** [comment]
Thanks for the reply. closing the issue.
