### ISSUE TITLE
Can't find model 'en_core_web_sm'

### ISSUE THREAD

**Issue by mug2mag** [facebookresearch/DPR#147]
Hi
I am trying to evaluation on NQ dataset:
```
python dense_retriever.py model_file=/home/dhf/git_local/DPR/downloads/checkpoint/retriever/single-adv-hn/nq
qa_dataset=nq_test ctx_datatsets=/home/dhf/git_local/DPR/downloads/data/wikipedia_split
encoded_ctx_files=[\"/home/duhuifang/git_local/DPR/downloads/data/retriever_results/nq/single-adv-hn/wiki_passages_*\"] 
out_file=/home/duhuifang/git_local/DPR/downloads/evaluation
```
Getting:
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by vlad-karpukhin** [comment]
It is Spacy's library dependency we use.
We will need to add it somehow to out setup script.
Running: 'python -m spacy download en_core_web_sm' should solve this issue.
Please refer to https://spacy.io/usage for installation instructions.

**Comment by mug2mag** [comment]
Very appreciated!

**Comment by xhluca** [comment]
@vlad-karpukhin It's possible via `install_requires` starting in pip>18, as discussed here: https://stackoverflow.com/a/53383704

Let me know if I can start a PR for this.
