### ISSUE TITLE
Pre-trained model and dataset for SQuAD reproduction

### ISSUE THREAD

**Issue by EDLMM** [facebookresearch/DPR#15]
Hi, I found that there is no option for reproducing the results for SQuADv1.1 experiments.
Though the dataset is with some bias compared NQ, I think it's still an important part of the paper since this dataset is common. 
Could you provide the dataset in DPR format and the pre-trained models for reproduction? Thx

**Comment by vlad-karpukhin** [comment]
Hi Yizhi,
Yes, we can provide Squad as well but many results and checkpoints we have not are on some old data formats not supported by our current DPR codebase. Since I don't have much time for all those conversions, could you please specifiy which files/resources you need and I will provide some links to what we have at the moment along with some format conversion instructions?

**Comment by okhat** [comment]
Somewhat related to this: SQuAD contains some pretty long answers. Do you keep all of them?

**Comment by EDLMM** [comment]
> Hi Yizhi,
> Yes, we can provide Squad as well but many results and checkpoints we have not are on some old data formats not supported by our current DPR codebase. Since I don't have much time for all those conversions, could you please specify which files/resources you need and I will provide some links to what we have at the moment along with some format conversion instructions?

Hi,  thanks for your reply. I'm trying to reproduce the single set training of SQUAD v1.1. So I think this might require the same format as `nq-train.json` and `nq-dev.json`, which are like:

```
[
  {
	"question": "'who sings does he love me with reba",
	"answers": ["...", "...", "..."],
	"positive_ctxs": [
		{
            "passage_id": '11828866',
            "score": 1000,
            "title": "...",
            "text": "....",
            'title_score': 1},
		...
	],
	"negative_ctxs": ["..."],
	"hard_negative_ctxs": ["..."]
  },
  ...
]
```
The dataset would contains positive, hard-negative and negative passages for each query. I would like to repeat the single-set training of the SQUAD and compare with your best checkpoints of squad single-set model. It would be great help if you could provide the processed dataset or data-preprocessing scripts in your repo. (With the scripts, I think the followers might try the model at other QA datasets for further usages.)
What's more, does the single-set training of SQUAD share the same setting of NQ training?

**Comment by vlad-karpukhin** [comment]
Our dense retriever SQUAD results are worse than BM25. This is specifics of that dataset which is very lexical matching oriented.
I added 2 files for SQUAD retriever training:
Please use data.retriever.squad1-train & data.retriever.squad1-dev resource keys to download them

**Comment by vlad-karpukhin** [comment]
> Somewhat related to this: SQuAD contains some pretty long answers. Do you keep all of them?

Hi Omar, 
I don't remember that we did any answer truncation for any of our datasets.

**Comment by EDLMM** [comment]
> Our dense retriever SQUAD results are worse than BM25. This is specifics of that dataset which is very lexical matching oriented.
> I added 2 files for SQUAD retriever training:
> Please use data.retriever.squad1-train & data.retriever.squad1-dev resource keys to download them

Thanks. The lexical matching hint is a good insight.

**Comment by vlad-karpukhin** [comment]
It seems this can be closed now.
