### ISSUE TITLE
Question about "Selecting a truncation strategy"

### ISSUE THREAD

**Issue by mug2mag** [facebookresearch/DPR#150]
when I trained the model by run `train_dense_encoder.py`, I got a ERROR log like:
```
We need to remove 11 to truncate the input but the first sequence has a length 4. 
Please select another truncation strategy than TruncationStrategy.ONLY_FIRST
```
`only_first` is a default value for `truncation strategy`, so my question is which truncation strategy can I choose to empirically improve the performance?  And how to change the value of `truncation strategy`. 
( If `truncation` is set `True`, which looks like a right and usual choice,  the function `_get_padding_truncation_strategies' will make the `truncation strategy=only_first` default.)

**Comment by vlad-karpukhin** [comment]
It is HF's error (https://github.com/huggingface/transformers/issues/5377)
Seems to be related to its specific version and patched.
Can you try to upgrade your transformers version?
