### ISSUE TITLE
Which HuggingFace tokenizers used in the new checkpoint?

### ISSUE THREAD

**Issue by shamanez** [facebookresearch/DPR#156]
For the previous DPR checkpoint, HF has given two tokenizers 

1. facebook/dpr-question_encoder-single-nq-base
2. facebook/dpr-question_encoder-multiset-base

I think these two works in the same way. But to clarify, could you please let me know about the tokenizer?

**Comment by vlad-karpukhin** [comment]
I honestly have no idea what those 'tokenizers' mean.
We used standard BERT-base tokenizer in DPR taken directly from HF codebase.

**Comment by shamanez** [comment]
Actually, it got sorted.  Seems like this DPR is using a bert-uncased tokenizer from HF :) cheers!
