### ISSUE TITLE
how to feed a custom json file to the training pipeline?

### ISSUE THREAD

**Issue by shamanez** [facebookresearch/DPR#158]
Hi, 

I created a JSON file with my own data, following the structure. Now I need to fine-tune the model with that. How can I use the custom json files?

**Comment by vlad-karpukhin** [comment]
Hi,
if you followed the same json format, just add a new dataset config like in this config: 
https://github.com/facebookresearch/DPR/blob/master/conf/datasets/encoder_train_default.yaml#L3
You can just use absolute file system path for the 'file' attribute.

**Comment by shamanez** [comment]
Thanks a lot.
