### ISSUE TITLE
 "data.retriever_results.nq.single-adv-hn.wikipedia_passages" in DPR/dpr/data/download_data.py has two different descriptions

### ISSUE THREAD

**Issue by XY2323819551** [facebookresearch/DPR#161]
There are two  identical files in DPR/dpr/data/download_data.py  ，but the descriptions are different，and I would like to know which description does file name "data.retriever_results.nq.single-adv-hn.wikipedia_passages" refer to?

  "data.retriever_results.nq.single-adv-hn.wikipedia_passages": {
        "s3_url": [
            "https://dl.fbaipublicfiles.com/dpr/data/wiki_encoded/single-adv-hn/nq/wiki_passages_{}".format(
                i
            )
            for i in range(50)
        ],
        "original_ext": ".pkl",
        "compressed": False,
        "desc": "Encoded wikipedia files using a single-adv-hn checkpoint("
        "checkpoint.retriever.single.nq.bert-base-encoder) trained on NQ dataset ",
    },
    "data.retriever_results.nq.single-adv-hn.wikipedia_passages": {
        "s3_url": [
            "https://dl.fbaipublicfiles.com/dpr/data/wiki_encoded/single-adv-hn/nq/wiki_passages_{}".format(
                i
            )
            for i in range(50)
        ],
        "original_ext": ".pkl",
        "compressed": False,
        "desc": "Encoded wikipedia files using a biencoder checkpoint("
        "checkpoint.retriever.single-adv-hn.nq.bert-base-encoder) trained on NQ dataset + adversarial hard negatives",
    },

**Comment by vlad-karpukhin** [comment]
That is a bug actually, I just removed one of the duplicates. Thanks for reporting
