### ISSUE TITLE
new hard-nagative examples

### ISSUE THREAD

**Issue by cn-boop** [facebookresearch/DPR#164]
How to use your new hard-negative examples which are mined by dpr itself?
I have tried some experiments but the results are similar with original dpr results, in which hard-nagetive examples are mined by BM25

**Comment by vlad-karpukhin** [comment]
Hi,
You can just use our example from the man README page "New model training combines two NQ datatsets:"

**Comment by languagescalingkdd** [comment]
Thank you. for your response. But I don't find details about "New model training combines two NQ datatsets:",  And I already find new nq-adv-hn-train dataset, and find it only contains hard-negative examples

**Comment by vlad-karpukhin** [comment]
Hi, 
there is basically very little  to explain in details - the new model is just trained using those 2 datasets, nothing more. All hyperparams are also the same.
