### ISSUE TITLE
Unexpected key(s) in state_dict: "embeddings.position_ids".  

### ISSUE THREAD

**Issue by yolsever** [facebookresearch/DPR#165]
Dear Vlad, 

Thank you so much for taking the time to answer all the issues raised here, that is very helpful. I trained the embeddings on my documents, that I formatted to be in the same way as the retriever training script expect - train_dense_encoder.py -. Then I tried using the trained embeddings to generate new embeddings - generate_dense_embeddings.py - for my documents using one of the checkpoints as the model. However, I get the following error. I would appreciate any help or insight.

> [2021-06-21 14:00:15,574][root][INFO] - Loading saved model state ...
> Error executing job with overrides: 
> ['model_file=/shared_folder/shared_notebooks/xxx/experiments/DPR/outputs/2021-06-18/15-43-23/outputs/dpr_biencoder.29',
> ctx_src=/shared_folder/shared_notebooks/xxx/experiments/DPR/downloads/data/retriever/posts_train.json']
> Traceback (most recent call last):
>  File "generate_dense_embeddings.py", line 140, in main
>     model_to_load.load_state_dict(ctx_state)
>   File "/opt/anaconda3/envs/dala/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for HFBertEncoder:
> 	Unexpected key(s) in state_dict: "embeddings.position_ids".  

Best regards,
Kaan

**Comment by vlad-karpukhin** [comment]
Hey,
Just use 'model_to_load.load_state_dict(ctx_state, strict=False)'
for this line : https://github.com/facebookresearch/DPR/blob/master/generate_dense_embeddings.py#L140
I will update the code soon

**Comment by yolsever** [comment]
Thank you, Vlad!

**Comment by Santosh-Gupta** [comment]
It seems that training and then saving the model creates 'embeddings.position_ids' in the state dictionary, when it wasn't there before. Would love to know the process behind this.

**Comment by wwfcnu** [comment]
> I also encountered this problem, how should I solve it?
