### ISSUE TITLE
BM25 retrieval result

### ISSUE THREAD

**Issue by sysu-zjw** [facebookresearch/DPR#169]
Hi, I wonder if you could provide the BM25 top-5 retrieval acc or the BM25 retrieval result on NQ test set? Thanks.

**Comment by vlad-karpukhin** [comment]
Hi,
Sorry, can't find them anymore.
But it is better to use a version of BM25 implemented in Pyserini toolkit: https://github.com/castorini/pyserini/blob/master/docs/experiments-dpr.md
