### ISSUE TITLE
questions about in-batch negatives in multi-GPU setting

### ISSUE THREAD

**Issue by menghuanlater** [facebookresearch/DPR#172]
Hello, Karpukhin
Thank you for opening the source code. This is a really excellent work. However, I have doubts about the number of In-batch negatives in multi-GPU setting. In your experiment, you use 8 GPUs, each with a batch size of 16. I want to know how the gold_passages and hard_negatives inside the batch on different GPUs are passed to other GPUs for use. For example, how the passages within the batch on cuda:0 are made available to the questions on cuda:1？

**Comment by vlad-karpukhin** [comment]
See this method:
https://github.com/facebookresearch/DPR/blob/master/train_dense_encoder.py#L646
We basically just use pytorch's dist.all_reduce utility.

**Comment by menghuanlater** [comment]
Thank you very much
