### ISSUE TITLE
When will the latest checkpoint be available on Huggingface?

### ISSUE THREAD

**Issue by tanmaylaud** [facebookresearch/DPR#174]
I would like to know if and when the latest ( Mar 2021) checkpoint will be available on Huggingface.
Is there anything I can help with in the process?

**Comment by vlad-karpukhin** [comment]
Hi @tanmaylaud ,
I'm not aware about HF's plans to be in sync with this repo.
The checkpoint provided is HF's bert-base model anyway, so you should be able to use it. I just don't know if HF has some extra requirements for the checkpoint to be compatible with their DPR API.

**Comment by tanmaylaud** [comment]
The checkpoints on HF were last updated on 25th. Nov 2020 (according to the model cards). 
I am looking for the checkpoint: 
checkpoint.retriever.single-adv-hn.nq.bert-base-encoder (March 2021)

**Comment by vlad-karpukhin** [comment]
yes, I understand that you meant the new one. I don't know about HF's plans.

**Comment by vinicius-cleves** [comment]
For future reference, you can use [this script](https://github.com/huggingface/transformers/blob/master/src/transformers/models/dpr/convert_dpr_original_checkpoint_to_pytorch.py) to convert a checkpoint to a format HF's transformers can load.

**Comment by tanmaylaud** [comment]
Thanks!
