### ISSUE TITLE
Did you use regex during to calculate top-k retrieval ? 

### ISSUE THREAD

**Issue by shamanez** [facebookresearch/DPR#175]
There are two methods given in the evaluation script, where one is with chunking strings and another one is with regex, do you see performance degrade when using the regex?

Thanks.

**Comment by vlad-karpukhin** [comment]
Hi @shamanez ,
The regexp validator is for datasets like TREC Q&A where every answer is a regexp expression itself. It is not supposed to be used for datasets like NQ or Trivia.

**Comment by shamanez** [comment]
Thanks a lot.
