### ISSUE TITLE
Ambiguity regards hard_neg_ctx_indices in dpr/models/biencoder.py

### ISSUE THREAD

**Issue by ali-abz** [facebookresearch/DPR#176]
Hi there,
I am modifying DPR codes so that it can handle graded training samples and I ended up in `dpr/models/biencoder.py:BiEncoder:create_graded_biencoder_input2`. I wanted to modify this section but I have to understand it first. I read the code and I feel there is something off with this part.
When we want to calculate `hard_neg_ctx_indices`, we assume that the first ctx in `ctx_tensors` is the positive one and as such, its index should be `current_ctxs_len`. But then, when we calculate `hard_neg_ctx_indices`, we only consider the positive context that we added before but not the `neg_ctxs` right after that positive:
https://github.com/facebookresearch/DPR/blob/49e5838f94ffced8392be750ded2a8fa4a14b5cf/dpr/models/biencoder.py#L298
I mean If we have two negatives with one positive, shouldn't we change
https://github.com/facebookresearch/DPR/blob/49e5838f94ffced8392be750ded2a8fa4a14b5cf/dpr/models/biencoder.py#L299
to something like `hard_negatives_start_idx = len(neg_ctxs) + 1` or just change the order of `all_ctxs` to `[positive_ctx] + hard_neg_ctxs + neg_ctxs`?

**Comment by ali-abz** [comment]
BTW, this repo and its paper are such great works. I am doing my whole master's theses around this code/paper. Thanks.

**Comment by vlad-karpukhin** [comment]
Hi @ali-abz ,
Yes, your suggested logic is correct. 
We just don't use neg_ctxs at all and hard_neg_ctx_indices is also not used later. 
It was once one of experimental features which I didn't clean form the code entirely.
So this doesn't affect anything if you don't modify other code parts.

**Comment by ali-abz** [comment]
I see. Thanks.
