### ISSUE TITLE
Generating Question's Dense Embeddings

### ISSUE THREAD

**Issue by hot-cheeto** [facebookresearch/DPR#180]
Hello, 
The script generate_dense_embeddings.py seems to generate only context embeddings, no matter if the encoder_type parameter is set to 'ctx' or not.  Further investigating, it seems that the code in line 134-139 is always using the context encoders' weights. I was able to made a small change in this part of the code to generate the question embeddings, by using the question encoder weights if encoder_type is not set to 'ctx'. 

original code :
    prefix_len = len("ctx_model.")
    ctx_state = {
        key[prefix_len:]: value
        for (key, value) in saved_state.model_dict.items()
        if key.startswith("ctx_model.")
    }

change to:
    key_name = 'ctx_model.' if cfg.encoder_type == 'ctx' else 'question_model.'
    prefix_len = len(key_name)
    ctx_state = {
        key[prefix_len:]: value
        for (key, value) in saved_state.model_dict.items()
        if key.startswith(key_name)
    }

I am wondering if I missed something in the documentation how to correctly generate the question embeddings, or was this a mistake ?  

Thanks :D

**Comment by vlad-karpukhin** [comment]
Hi @hot-cheeto ,
Yes, generate_dense_embeddings is supposed to generate passages embeddings only. Query embeddings are generated on the fly when you need them to do the evaluation when using dense_retriever.py

**Comment by vlad-karpukhin** [comment]
Also, there is no code that reads query embeddings to use for evaluation, so you will also need to modify downstream code in order to use this generated query embeddings instead of generating the on the fly.
