### ISSUE TITLE
Siamese vs BiEncoder

### ISSUE THREAD

**Issue by zhiqihuang** [facebookresearch/DPR#188]
Hi, thank you for providing the code. I have a question about Siamese vs BiEncoder.

So why use two separate encoders instead of one shared encoder for both query and document?

Comparing DPR with ColBERT, they are both pushing the query document interaction after the model output so that indexing is possible. And instead of reranking, we can retrieve from the whole collection. 

But different from ColBERT, DPR has two encoders, which doubles the parameter. So what if we use one shared encoder in DPR?

**Comment by vlad-karpukhin** [comment]
I tried to use a shared encoder and the results were worse. ColBERT is quite a different model overall.
I've heard about the DPR setup with shared  encoder that worked well, as far as I remember they used extra layer norm on top of the encoder and cosine similarity.
