### ISSUE TITLE
Retriever inference result

### ISSUE THREAD

**Issue by zhenduow** [facebookresearch/DPR#19]
Hi! 

I run the retriever inference as instructed. But I do not understand its output. Is there another instruction for how to use the generated dense embeddings?

Thank you very much!

**Comment by vlad-karpukhin** [comment]
Hi Zhenduo,
Do you mean you ran dense_retriever.py with already generated wikipedia embeddings?

**Comment by zhenduow** [comment]
Yes. I have the generated file but I cannot read it. How should I load it?

**Comment by vlad-karpukhin** [comment]
encoded wikipedia files are python's "pickled" data. 
Have a look at this example in readme https://github.com/facebookresearch/DPR#retriever-validation-against-the-entire-set-of-documents to run dense_retriever and see the full retrieval results
