### ISSUE TITLE
About the NQ model trained with mined hard negatives.

### ISSUE THREAD

**Issue by shunyuzh** [facebookresearch/DPR#193]
Hi,
Thanks for your awesome work. 

I know the new DPR model (Top100=87.29) was trained from scratch using the new mined hard negatives combined with the original NQ training data. So have you tried training the model with only new mined hard negatives? Is it worse than the former version?

Thanks.

**Comment by vlad-karpukhin** [comment]
Hi @Dopaminezsy ,
No, I haven't tried to train just on the new hard negatives. You can easily try that and share the results here :)
