### ISSUE TITLE
Question about answer quality quantification

### ISSUE THREAD

**Issue by churinga** [facebookresearch/DPR#200]
Hi. We have encountered some difficulty identifying _bad_ answers produced by the DPR model. The model's output reader score and prediction score seem unbounded and unnormalized, making it impossible to compare with any threshold. Any suggestions on how to identify whether the answer produced by the model is actually not likely a good answer? Thanks a lot!

**Comment by vlad-karpukhin** [comment]
I'd recommend to use other reader models. Ours is a pretty old one already.
Have a look at https://github.com/facebookresearch/FiD
AFAIK that is the current SOTA reader model.

**Comment by churinga** [comment]
Thank you for the quick reply, and for pointing me to the better SOTA option! I will read more about FiD, but from what I have seen so far, the same problem may also apply to FiD, i.e. how to compare answer quality horizontally? I.e. given N different questions, how to gauge, with a unified standard, the quality of the answers generated by either DPR- or FiD-based method, so that some low quality answers can be filtered? It seems to me that the scores returned by the models are only directly comparable among the passages retrieved for the same question, but cannot be head-to-head compared with scores of passages for other questions. 

Thanks again.

**Comment by vlad-karpukhin** [comment]
Hi,
We just do exact match check - if any of the answer variants (if provided) is equal to the generated/extract span, it is considered a correct hit. We use some simple text normalization for this equality check, but nothing special.

**Comment by churinga** [comment]
I see. Thanks for the replies. Closing this issue now.
