### ISSUE TITLE
Question about reader training

### ISSUE THREAD

**Issue by TZeng20** [facebookresearch/DPR#204]
Hi,

Am wondering if you could help me understand more about the input for training the **reader**?

1. Are the positive and negative contexts for each question generated using the retriever before training or during training?
2. What does a training batch look like? Is [`sample_batch`](https://github.com/facebookresearch/DPR/blob/644d4fe699b3cee16c4324509c1cedc0168d9461/train_extractive_reader.py#L283) a batch of  question, passage, answer pairs and then [`inputs`](https://github.com/facebookresearch/DPR/blob/644d4fe699b3cee16c4324509c1cedc0168d9461/train_extractive_reader.py#L294) are the transformer model inputs of shape (num_questions, num_passages, seq_length)?

**Comment by vlad-karpukhin** [comment]
Hi @TZeng20 ,
1. positive and negative contexts for each question are generated before the training process. We use own DPR dense index to mine positives and negatives contexts (that is the point of open domain setup). We also use gold positive passages as positives  provided by datasets and some extra heuristics regarding the choice of retrieved passages for the reader training.  
2. The sample_batch contains a set of questions each accompanied with a pool of positive and hard negative passages. The inputs are what actually go into the model. create_reader_input() selects exactly one positive and a number of negative contexts from the provided pools, concatenates with the questions and tokenizes them converting to tensors.

Hope this clarifies your questions
