### ISSUE TITLE
Importerror

### ISSUE THREAD

**Issue by Facico** [facebookresearch/DPR#206]
Hello,
after I installed it， I meet the importerror “ImportError: cannot import name 'regex_match' from 'dpr.data.qa_validation'”.
and the program likes this "import dpr.data.qa_validation"(just one line)
I have not encountered similar problems with previous versions of this repository.

I would appreciate it if someone could help me.  Thanks.

**Comment by Facico** [comment]
I think the problem might be that table.py import from qa_validation.py and create a cyclic dependency

**Comment by vlad-karpukhin** [comment]
Thanks @Facico for reporting the bug. I've just put a temporal fix.
