### ISSUE TITLE
How to get ctx_encoder from the checkpoint?

### ISSUE THREAD

**Issue by ali-abz** [facebookresearch/DPR#216]
Hi,
I was wondering if I could get ctx_encoder (or the question encoder) from the checkpoint that DPR makes. I need to have a single model that can be loaded with torch or hugging face or something like that. I would appreciate if you could help me.
Thanks.

**Comment by vladk232** [comment]
Hi @ali-abz , this codebase is no longer supported, sorry.

**Comment by ali-abz** [comment]
Oh I see. Thanks for your great work. I'll find a way.
