### ISSUE TITLE
Loss across the nodes....[multi-gpu training]

### ISSUE THREAD

**Issue by gabinguo** [facebookresearch/DPR#218]
Hello,

Thanks for sharing this great work. 
I have a question about the multi-gpu training: 

After the communication `all_gather_list(...)` function, all the nodes will have the same representations but in different positions of the vector and also the `positive_idx_per_question` list will also have the same content but in different node-dependant orders, so actually the NLL loss computed by all the nodes will be the same as well right?
Thanks in advance for any replies : )

**Comment by vladk232** [comment]
Hi @gabinguo ,
yes, the loss must be identical on all the nodes (since the similarity matrix is identical). But each node computation graph is based on node's own query and passages inputs and thus the gradients will be different.

**Comment by gabinguo** [comment]
Nice!! Thanks so much for the reply 👍👍👍
