### ISSUE TITLE
How to generate gold_passage_info?

### ISSUE THREAD

**Issue by Yifan-Gao** [facebookresearch/DPR#23]
Hi, thanks for the great work. May I know how `gold_passages_info.nq_{train|dev|test}` are generated? I guess they might come from NQ dataset, but is there any standard way to generate these files?

**Comment by vlad-karpukhin** [comment]
Hi Yifan,

Yes, gold_passages_info.nq_ are taken directly from the original 'official' NQ dataset files.
The script to generate those is unfortunately not a part of the repo, but the logic is quite straightforward. 

Thanks,
Vlad

**Comment by Yifan-Gao** [comment]
Thanks Vlad. I will try to generate these files on my own and see if I can replicate the results.
