### ISSUE TITLE
About inference for the reader model

### ISSUE THREAD

**Issue by Yifan-Gao** [facebookresearch/DPR#28]
Hi DPR authors, thanks for the great work! I am wondering why the reader model do inference by firstly selecting the top reranked passage within the `passage_thresholds`, and then select the best span within the top ranked passage. 

https://github.com/facebookresearch/DPR/blob/d7ba973ab2d862d1b44c2402b59b1ca2a362ee96/train_reader.py#L334-L336

https://github.com/facebookresearch/DPR/blob/d7ba973ab2d862d1b44c2402b59b1ca2a362ee96/train_reader.py#L343-L344

In my understanding, spans in `nbest` are sorted according to their corresponding passage selection score, so the best span from the passage with the highest passage selection score will be chosen. This makes the reader model depends highly on the top1 accuracy of passage selection (reranking).

Will it be better if the reader rerank all spans from all passages according to the sum of the relevance score and the span score?

BTW, I have two minor implementation questions:
- The question-title-passage encoding looks like this `[CLS] question [SEP] title [SEP] passage [PAD] [PAD] ... [PAD]`, is there a missing `[SEP]` at the end of the passage?
- The reader model is trained by maximizing the marginal likelihood of all matched answer spans. During the inference time, if answers from different passages have the same string, why don't merge them by summing up their scores?

**Comment by vlad-karpukhin** [comment]
Hi Yifan,

Yes, your understanding is correct about our reader logic. It select the span first based on its relevance logit score only.
We experimented with the combined score model first but got worse results. 
There is however a better reader model - one needs to use the combined score per predicted span spans, grouping them by their string representation. We've got + 1-2 EM points using such schema.
This is not currently implemented in DPR codebase.

The answers for your questions:
- Yes, tailing SEP is missing in the reader, you may try to experiment with that added. I don't expect it will change final results.
- Yes, see my comment above about a better reader model which boosts same predicted spans. Though I feel like a lot of identical spans from multiple passages are often false positives or not always correct.

**Comment by Yifan-Gao** [comment]
Thanks for your detailed reply!

**Comment by Yifan-Gao** [comment]
Hi @vlad-karpukhin , may I ask another question about the reader logic? 

https://github.com/facebookresearch/DPR/blob/d663f68b25b180243eeabda40b74f5d55c34b0a3/dpr/models/reader.py#L93

For loss calculation, why it uses `max(dim=1)` over passages? If there is two positive passages sampled for the question, then the logic here is to select the passage which the reader model is not very confident of (higher loss score).

Am I correct? Why not take all loss scores into maximum marginal likelihood calculation (`_cal_mml`)?

**Comment by Yifan-Gao** [comment]
Also, since current reader model does not do [global normalization (or shared normalization)](https://www.aclweb.org/anthology/P18-1078/) over passages, probabilities of answers in different passages are not comparable.

**Comment by Yifan-Gao** [comment]
Oh, I understand the logic here, thank.
