### ISSUE TITLE
Retriever Inference Time 

### ISSUE THREAD

**Issue by ashispapu** [facebookresearch/DPR#30]
Thanks for the great work and making it available to us. I could set up and run the DPR system with pre-trained models. However I observed it takes more than 20 seconds to fetch top 10 passages from the end to end system for a given query. I'm using the faiss package which is integrated with the retriever. Am I missing something here ? If this is the case, is there any way to reduce the inference time to make it effective in  real time QA applications.

Looking forward to your valuable feedback.

**Comment by vlad-karpukhin** [comment]
Hi Ashis,

By default our dense_retriver.py uses exhaustive search ('Flat' index type in FAISS). That is why it has large latency and it suitable only for research evaluations, not for production usage.

You can enable a more efficient HNSW index type (see implementation here https://github.com/facebookresearch/DPR/blob/master/dpr/indexer/faiss_indexers.py#L99) by specifying --hnsw_index flag.
However that index takes a lot of RAM (~200 GB for our wikipedia size) and takes about 9 hours for indexing.

You can serialize it once it is indexed and then deserialize it from files for subsequent usage.
See the code here
https://github.com/facebookresearch/DPR/blob/master/dpr/indexer/faiss_indexers.py#L50

You will need to write your own retriever though, but you have all the subcomponents ready in DPR.

**Comment by ashispapu** [comment]
Thanks @vlad-karpukhin for the response. I understand the limitations, would explore more to tune/fit it for the task I'm doing.
