### ISSUE TITLE
Reproducing Table 2 of DPR paper

### ISSUE THREAD

**Issue by aarzchan** [facebookresearch/DPR#34]
Hi! Does the repo include code for reproducing Table 2 ("Top-20 & Top-100 retrieval accuracy on test sets...") of the DPR paper?

**Comment by vlad-karpukhin** [comment]
Hi,
Yes, the models we provide should be enough to reproduce IR accuracy for the dense only schema but only for NQ & Trivia datasets (the others have their evaluation methods specifics and we deliberately didn't include them in the repo).
In fact, NQ model checkpoint should be even 2-3 accuracy points higher than reported in the Table #2

**Comment by aarzchan** [comment]
I see. To clarify, this [line](https://github.com/facebookresearch/DPR/blob/master/dense_retriever.py#L264) in `dense_retriever.py` produces the retrieval accuracy results, right?

**Comment by vlad-karpukhin** [comment]
Correct, it generates top-k accuracy (may be with false positives) for every k from 1 to 100.

**Comment by vlad-karpukhin** [comment]
it seems this can be closed now
