### ISSUE TITLE
Questions about the data of TriviaQA

### ISSUE THREAD

**Issue by morningmoni** [facebookresearch/DPR#35]
Greetings,

I have 2 questions regarding the data of TriviaQA as follows:

1. [Reader training] If I understand correctly, multiset refers to training the retriever on multiple datasets rather than the reader. Then the pickle files data.reader.trivia.multi-hybrid.train_[0-8].pkl (total size is 66,544) are questions from TriviaQA only, right? Could you provide DPR's json results similar to data.retriever_results.nq.single.[train/dev/text] in addition to the pkl files since some samples are filtered in pkl for reader training (78,785 -> 66,544)?

2. [Retriever Training] data.retriever.nq-train (size 58,880) is the subset after pruning but data.retriever.trivia-train (size 78,785) appears to be the whole training set (referring to 60,413 in Table 1)?

Thank you!

**Comment by vlad-karpukhin** [comment]
Hello,

1. pickle files data.reader.trivia.multi-hybrid.train_[0-8].pkl  are the processed results from the retriever trained on a multi-set using the hybrid retriever approach where both dense and standard bm25 works together in the way described in the paper. The filtered samples are those without any positive passage found and thus useless for our reader training. Unfortunately we have them only in some other custom non DPR format. I don't have trivia's hybrid results in the current DPR format, but a in slightly different json format. I can share it if you can transform it at your side.

2. We applied gold passages mapping from original passages to our wikipedia snapshot passages for NQ and thus lost some portion of data (~ 25%). But there were no such mapping for Trivia, so the size if full.

**Comment by morningmoni** [comment]
Thanks for your reply! I'll appreciate it if you could share the link of json files here (or email if you prefer yuningm2@illinois.edu).

**Comment by vlad-karpukhin** [comment]
I put 3 files under:
https://dl.fbaipublicfiles.com/dpr/data/retriever_results/multi/trivia-hybrid-{dev|train|test}.json.gz

please have a look.
You will need to modify those jsons to be like current DPR's retriever output format.

**Comment by morningmoni** [comment]
Thanks! I found that the only non-empty ctx lists are 'positive_ctxs', which all have a length of 100. Shall I simply treat it as 'ctxs' as in the DPR format? Just to clarify, 'negative_ctxs', 'distant_negatives', 'distant_gold_negatives', 'matched_ctxs' are not used, right (i.e., the ctxs/samples are all from Trivia)? 

I have reproduced the reader training using the pkl files and assume that if I run with the json file using the same data preprocessing parameters `DEFAULT_PREPROCESSING_CFG_TRAIN` as NQ I could get the same/similar results, right?

**Comment by vlad-karpukhin** [comment]
Yes, those positive_ctxs are actually what was returned from the retriever.
But this format is a bit different from DPR currently uses for the reader input. PLease have a look at NQ result jsons and modify accordingly.
Yes, you should get same or close results.
