### ISSUE TITLE
Change link in paper to this repo

### ISSUE THREAD

**Issue by tuzhucheng** [facebookresearch/DPR#36]
Thank you for open-sourcing this great work!

In the arXiv paper the footnote link to the code is https://fburl.com/qa-dpr. I believe that is an internal FB link :). You might want to change it to point to this GitHub repo instead.

**Comment by vlad-karpukhin** [comment]
Hi Michael,
thanks for this reminder. We are aware of that, but can't update the paper in arXiv at the moment.
