### ISSUE TITLE
Can pre-trained model checkpoints be loaded as hugging-face transformer model?

### ISSUE THREAD

**Issue by NThakur20** [facebookresearch/DPR#37]
Hello, 

I wanted to load the checkpoint - "checkpoint.retriever.multiset.bert-base-encoder" as a huggingface transformer model, i.e. will I be able to load it using something similar like the example code mentioned below?

This is something which I would ideally like to have -
`from transformers import AutoModel`
`model = AutoModel.from_pretrained(path_to_checkpoint)`

At the moment, I see in files - `dense_retriever.py` and `generate_dense_embeddings.py`, the checkpoint model, is loaded as the bi-encoder class defined as - `models/biencoder.py`
`print(type(encoder))`
`>>> <class 'dpr.models.biencoder.BiEncoder'>`

Kind Regards,
Nandan Thakur

**Comment by vlad-karpukhin** [comment]
Hi Nandan,

We store some extra information in our checkpoints. You can extract HF transformer model by extracting the corresponding state dicts from our hierarchy:
root->model_dict->question_model for question  encoder
root->model_dict->ctx_model for passages encoder.
Those should be compatible with HF's base transformers.

**Comment by NThakur20** [comment]
Thanks @vlad-karpukhin for the prompt response.

The last question would be, have you evaluated DPR against the MS-MARCO dataset? If yes, is there any such code available? if no, are you planning to implement it in the future or not? 

Kind Regards,
Nandan Thakur

**Comment by vlad-karpukhin** [comment]
Sorry, we haven't tried MS-MARCO and don't plan to at the moment.

**Comment by NThakur20** [comment]
Alright then. Thanks.
