### ISSUE TITLE
Question regarding dense_retriever arguments

### ISSUE THREAD

**Issue by erthher** [facebookresearch/DPR#39]
What is the "encoded_ctx_file" for the dense_retriever.py script?

 
 ---
I am trying to use the pretrained retriever to create the input files for the reader model.
I've used the download_data.py script to download:

The retriever checkpoint into: `checkpoint/retriever/single/nq/bert-base-encoder.cp`
Wikipedia tsv file into: `data/wikipedia_split/psgs_w100.tsv`
QA data into: `data/retriever/qas/nq-*.csv`

But I am not sure what is the "encoded_ctx_file" refered to in the following running instruction:

`python dense_retriever.py --model_file ${path to biencoder checkpoint}  --ctx_file  {path to all documents .tsv file} --qa_file {path to test|dev .csv file} --encoded_ctx_file "{encoded document files glob expression}" --out_file {path to output json file with results} --n-docs 200`

**Comment by vlad-karpukhin** [comment]
Hello there,

encoded_ctx_file is a glob expression for all the files with passage embeddings (entire wikipedia) which were generated as the output of running generate_dense_embeddings.py.

**Comment by soheeyang** [comment]
For example, in order to use the dense embeddings downloaded with `python data/download_data.py --resource data.retriever_results.nq.single.wikipedia_passages`, you can use `--encoded_ctx_file 'data/retriever_results/nq/single/wikipedia_passages_*'`.
