### ISSUE TITLE
Questions about the Retriever input data format

### ISSUE THREAD

**Issue by AkariAsai** [facebookresearch/DPR#42]
Hi, thank you so much for open-sourcing DPR! I have some questions about the [Retriever input data format](https://github.com/facebookresearch/DPR#retriever-input-data-format). 

Given the paper, the best performance comes from the `Gold` setting + 1 `BM25` paragraph, in which  (from my understanding) the negative examples are in-batch gold paragraphs and 1 BM 25 paragraphs. On the other hand, in the provided retriever’s `nq_train.json` data, there are multiple `positive_ctxs` and 50 `negative_ctxs` and a lot of `hard_negative_ctxs`, while it seems that those `negative_ctxs` will not be used [by default](https://github.com/facebookresearch/DPR/blob/ff0fff500f083fe8a33a8e09bde36927dec6ac2f/train_dense_encoder.py#L518#L521 )) and only one paragraph from `hard_negative_ctxs`  will be used.  

First, what is the difference between the `negative_ctxs` and `hard_negative_ctxs`? 
Second, how those negative paragraphs are selected? 
Also, there are multiple `positive_ctxs` in `nq_train.json`. According to the paper, the positive examples for NQ and SQuAD are the preprocessed paragraphs corresponding to the original reference paragraphs in the original NQ / SQuAD datasets. How are the positive paragraphs in `nq_train.json` are selected? 

>  For SQuAD and Natural Questions, since the original passages have been split and processed differently than our pool of candidate passages, we match and replace each gold passage with the corresponding passage in the candidate
pool.

**Comment by vlad-karpukhin** [comment]
Hi Akari,

As of the negatives provided. Yes, we don't use 'negative_ctxs' by default but you can use that for experimentation. 
All the negatives (and positives, if you enable them explicitly) are the pools the selected from. They are SAMPLED from those 50 or 30 lists on every epoch and every batch. So, they may not be the same from one epoch to another for every given question sample. 

"First, what is the difference between the negative_ctxs and hard_negative_ctxs?" - negative_ctxs are basically just some random negatives across entire wikipedia provided for experimentation and consistency if you want to use them. hard_negative_ctxs are those returned by bm25 for each query but have no answer spans.

"How are the positive paragraphs in nq_train.json are selected?" - by default, only the first "gold" positive is used. But again you can opt to use all or part of them in the random or deterministic way. We found that using the gold ones slightly (1-1.5 points) improve the results. 
We mined those "gold" passages using the original ones (provided by datasets) and our wikipedia snapshot split. If we don't do that, the model easily recognizes original gold passages vs our wiki passages even without questions (we just trained a classifier to separate the original gold vs ours and it works pretty well). There is some bias which we were not able to find and had to do that mapping.

Hope this answers your questions.

**Comment by zhenduow** [comment]
> Hi Akari,
> 
> As of the negatives provided. Yes, we don't use 'negative_ctxs' by default but you can use that for experimentation.
> All the negatives (and positives, if you enable them explicitly) are the pools the select from. They are SAMPLED from those 50 or 30 lists on every epoch and every batch. So, they may not be the same from one epoch to another for every given question sample.
> 
> "First, what is the difference between the negative_ctxs and hard_negative_ctxs?" - negative_ctxs are basically just some random negatives across entire wikipedia provided for experimentation and consistency if you want to use them. hard_negative_ctxs are those returned by bm25 for each query but have no answer spans.
> 
> "How are the positive paragraphs in nq_train.json are selected?" - by default, only the first "gold" positive is used. But again you can opt to use all or part of them in the random or deterministic way. We found that using the gold ones slightly (1-1.5 points) improve the results.
> We mined those "gold" passages using the original ones (provided by datasets) and our wikipedia snapshot split. If we don't do that, the model easily recognizes original gold passages vs our wiki passages even without questions (we just trained a classifier to separate the original gold vs ours and it works pretty well). There is some bias which we were not able to find and had to do that mapping.
> 
> Hope this answers your questions.

Hi vlad-karpukhin, 

I want to tune the pretrained checkpoint on my dataset other than google NQ. According to the reply you give, are the only thing that's must-have in the training data the 'question', 1 'gold ctx' as 'positive_ctxs', and 1 'hard_negative_ctxs'. And if I want to be fancier, I can add some 'negative_ctxs' ? And 'answers' is not hard-required?(as I am tuning it on a conversation)

What is an ideal set of numbers of candidates for tuning you would recommend?

Thank you so much!

**Comment by vlad-karpukhin** [comment]
Hi Zhenduo,

The optimal settings we found are the default ones - 1 positive, 1 hard negative, the bigger effective batch size, the better.
Yes, answers are not required for training in theory, but I haven tested that.

**Comment by zhenduow** [comment]
> Hi Zhenduo,
> 
> The optimal settings we found are the default ones - 1 positive, 1 hard negative, the bigger effective batch size, the better.
> Yes, answers are not required for training in theory, but I haven tested that.

Thank you! I will try the optimal settings.

**Comment by AkariAsai** [comment]
Thank you so much for your detailed response, @vlad-karpukhin ! The information is really helpful. I will train DPR on our own data following your suggestion! 

I have a followup question related to the procedures for fine-tuning on our own data. Could you share the script to create a tsv file of the whole Wikipedia paragraph information (`inpsgs_w100.tsv`)? I'm trying to run DPR on our own question-passage data (the data is still Wikipedia but from different timestamps), and wondering if the script to create the original paragraphs files from the Wikipedia dump is available.

**Comment by vlad-karpukhin** [comment]
Hi Akari,
We used a bunch of tools and scripts from different people adn code repos and I don't have all the wikpedia preparation pipeline unfortunately.

We basically did 3 steps:
1. Process initial wikipedia dump from  https://archive.org/download/enwiki-20181220/ using WikiExtractor tool and a command like:
python WikiExtractor.py --json --filter_disambig_pages 

2. We used some extra filtering steps from DrQA datasets.

3. Split the pages into 100 words passages using Spacy en-web tokenizer

**Comment by AkariAsai** [comment]
Thank you for the detailed instructions! I'll try to build a similar preprocessing pipeline for our Wikipedia dump. I'll close this issue. Thanks again for your detailed answers!

**Comment by Atomu2014** [comment]
> Thank you for the detailed instructions! I'll try to build a similar preprocessing pipeline for our Wikipedia dump. I'll close this issue. Thanks again for your detailed answers!

Hi, have you reproduced the preprocessing pipeline? Can you share the scripts? Thanks!

**Comment by searchivarius** [comment]
Hi @vlad-karpukhin thanks a lot for all the hard work, putting it all together, and publishing **both** data and code.  This has been clearly a game changer  for neural retrieval.

However, we are still very confused with respect to what you are considering **gold**. 

In the paper, you say that "gold" is a negative example:
```
We consider
three different types of negatives: (1) Random: any
random passage from the corpus; (2) BM25: top
passages returned by BM25 which don’t contain
the answer but match most question tokens; (3)
Gold: positive passages paired with other questions
which appear in the training set.
```

Here you talk about gold positives:
```
"How are the positive paragraphs in nq_train.json are selected?" - by default, only the first "gold" positive is used. But again you can opt to use all or part of them in the random or deterministic way. We found that using the gold ones slightly (1-1.5 points) improve the results.
```

Could you elaborate further? My understanding is that 
1. positive == relevant
2. these positives (at least for SQuAD and Natural Questions) are BM25-selected passages that **containing an answer?**.

Am I wrong?

**Comment by Rosarubu** [comment]
Hi @searchivarius, to my understand , the "Gold" they mentioned in the third types of negatives means in-batch negative, that when you process a batch of samples, the other questions' positive passage(Gold one) are used as the nagetive passages for this question.

**Comment by searchivarius** [comment]
@Rosarubu that's my understanding as well, but in this thread @vlad-karpukhin refers to them as positives:
```
by default, only the first "gold" positive is used
```

Also, it seems that relevant documents are those that contain an answer as a string: Both for training and testing. However, we are not 100% sure, because the paper seems to be unclear with respect to explaining this.

**Comment by Rosarubu** [comment]
> We mined those "gold" passages using the original ones (provided by datasets) and our wikipedia snapshot split.
Hi @vlad-karpukhin , I have a question abou the "gold passage provide by datasets", for NaturalQuestion, do you mean the "long_answer_candidates" they provide?

**Comment by searchivarius** [comment]
@Rosarubu sorry, but t does not explain how gold can be positive and negative at the same time.

**Comment by Rosarubu** [comment]
> @Rosarubu that's my understanding as well, but in this thread @vlad-karpukhin refers to them as positives:
> 
> ```
> by default, only the first "gold" positive is used
> ```
> 
> Also, it seems that relevant documents are those that contain an answer as a string: Both for training and testing. However, we are not 100% sure, because the paper seems to be unclear with respect to explaining this.

Emm.. I am not sure about how they produce positive passages either. I agree with you that the relevant documents are those that contain an answer as a string. Thus there are multiple positive passages in retriever’s nq_train.json data. But how they decide which one is the **first gold positive** is unclear to me.

**Comment by searchivarius** [comment]
@Rosarubu as a reminder the paper states that "gold" passages are negatives, not positives.

**Comment by Rosarubu** [comment]
> But in the paper they are negative with respect to the question for which they are being sampled.

I think they are negative with respect to **other questions in the same batch** instead of the question for which they are being sampled.

**Comment by searchivarius** [comment]
@Rosarubu this is just another way to state basically the same thing, which only reinforces the fact that "gold" positives are negatives. it doesn't make them any more positive.

**Comment by vlad-karpukhin** [comment]
Hello,
Sorry for confusing names.
Gold negatives are negatives first of all.
Being positive or negative in our notation is a function of BOTH passage &
a question F(passage, question).
So, every passage can be both negative for some question (doesn't have any
of its answer spans) and positive for another one (does have any of its
answer spans). The presence or absence of an answer may be of course a sign
of false positive and false negative samples.
The gold negatives in the paper you are referring to are taken from other
question's positives.
For example, let's assume we have two questions q1 & q2 and their
respective positives ctx1 & ctx2 and F(q1, ctx2)==Negative and  F(q2,
ctx1)==Negative.
In this case we call ctx2 a 'gold negative'  for q1 and ctx1 a 'gold
negative'  for q2.

As of how we selected the subset of the original question samples for the
NQ dataset - we followed the same process described in the ORQA paper and
got the same num of samples. This is a subset of samples with 'relatively'
(<=5 tokens?) SHORT answers.
As of the gold positives provided by NQ dataset -  we found it has some
inherent text formatting bias vs the wikipedia snapshot we extracted using
WikiExtractor library. So the model could basically be trained as the
classifier to distinguish between passages in wiki vs NQ even without
questions.
Our workaround for this issue was that we mapped every NQ (gold positive)
passages to its counterpart in our wikipedia passages split. We did that by
indexing all wikipedia passages in Lucene BM25 index and used the original
NQ passages text as search queries followed by an answer span presence
filter. We lost ~ 25% of the training set on this step.

Hope this clarifies your understanding.

**Comment by searchivarius** [comment]
Hi @vlad-karpukhin thank you! Do I understand it correctly that when you say "NQ gold positives" you refer to the positives provided by the creators of NQ? And, obviously, these are different from your gold passages.

**Comment by vlad-karpukhin** [comment]
Correct, they provide passage 'candidates' in the NQ dataset.

**Comment by Rosarubu** [comment]
Hi @vlad-karpukhin , thanks for the detailed explanation. For 'passage candidates', do you mean the "long_answer_candidates" in NQ dataset? If so, for some questions that have several answer candidates, and more than one wiki passages remained after you search the wiki using BM25 and filter answer span, how do you decide which one is the "real gold" one?
