### ISSUE TITLE
Confusion about reader data and retrieval results

### ISSUE THREAD

**Issue by aarzchan** [facebookresearch/DPR#47]
I have some confusion regarding the reader data provided in `data.reader.nq.single` and the retrieval results provided in `data.retriever_results.nq.single.[train|dev|test].json`.

From my understanding, the reader data is obtained by running `dense_retriever.py` on the dense embeddings generated via `generate_dense_embeddings.py`. According to Table 2 of the paper, Top-20 and Top-100 retrieval accuracy for NQ (Single-DPR) are 78.4% are 85.4%, respectively. Thus, my interpretation is that, for k <= 100, almost all of the Top-k passages could be used as reader positives, since they contain the answer span.

However, for each question in the provided reader data, almost all of the passages are negative. Specifically, for both reader train and dev data, the average number of positive passages per question is less than 4. 

Also, when I checked the provided retriever results, I found that the retrieval accuracy (i.e., average percentage of Top-100 passages per question with `has_answer = True`) for these datasets is only around 8%, which seems a lot lower than the 85.4% reported in Table 2.

Could you please help me better understand what is happening here? Thanks!

**Comment by vlad-karpukhin** [comment]
"Thus, my interpretation is that, for k <= 100, almost all of the Top-k passages could be used as reader positives, since they contain the answer span." - sorry but this is not a correct interpretation.

Top 100 accuracy of 85.4% means that 85.4% of samples have at least ONE positive(possibly false positive) passage in the top 100 retrieved results.

Also, please note NQ has an extra reader data preprocessing step which takes into account gold passages and their links to wikipedia pages and creates pools of ctx+ and ctx- based differently for questions with positive passages from gold pages and the rest. This processing is for NQ only and only for train dataset (that would have been cheating to do that for the test/dev sets). See my comments for this issue: https://github.com/facebookresearch/DPR/issues/46

**Comment by aarzchan** [comment]
Ah, I see. I feel the caption for Table 2 is a bit ambiguous then, since it could be interpreted both ways: "Top-20 & Top-100 retrieval accuracy on test sets, measured as the percentage of top 20/100 retrieved passages that contain the answer." Why would there be false positives though?

Also, if the extra preprocessing step is only for the train set, then why can we specify --gold_passages_src_dev?

**Comment by vlad-karpukhin** [comment]
Yeah, the description sounds confusing to me now.
" Why would there be false positives though?" - cause we consider a passage positive if it contains one of question answers. It it may be a spurious match.

"Also, if the extra preprocessing step is only for the train set, then why can we specify --gold_passages_src_dev?" - good question, it can be removed. 
But It doesn't matter for dev set cause it is just to select the best checkpoint. Reported numbers are for test set. (Our dev set is not official anyway)

**Comment by aarzchan** [comment]
Hmm, I don't understand. If a question has multiple gold answers, then shouldn't any passage containing any of the answers be a valid match? Why would each gold answer be considered individually when evaluating retrieval?

**Comment by vlad-karpukhin** [comment]
"If a question has multiple gold answers, then shouldn't any passage containing any of the answers be a valid match?" -why should it be a valid match?

Here is a real example from NQ:

Question: "when did the dallas cowboys win their last playoff game" answer: 2016
One of the top retrieved passages:
"In 2017, the team initially announced that they will wear blue jerseys at home on a more regular basis, only to rescind soon after. In 2015, the Cowboys released their Color Rush uniform, featuring a variation of the 1990s \"Double Star\" alternates with white pants and socks. The uniform was first used in a Thanksgiving game against the Carolina Panthers and in subsequent \"Thursday Night Football\" games during the 2016 and 2017 seasons."

It contains "2016" answer span, but is this true positive passage? sure, it is not.

"Why would each gold answer be considered individually when evaluating retrieval?" - this is how NQ(and Trivia) was designed - multiple versions of answers, any match is considered as a hit. TREC, for example has answers as regular expressions. WebQ answers should be enity-normalized.
Each dataset may be different for representing answers and have different requirements.

**Comment by aarzchan** [comment]
Okay, I understand what you mean now. Thanks!
