### ISSUE TITLE
dense_retriever not enough values to unpack

### ISSUE THREAD

**Issue by szhang42** [facebookresearch/DPR#53]
Hello, 

While I was running dense_retriever.py, I incurred the below problem. I am a bit confused about the below problem. Is this issue due to that I set --num_shards =20 and only run --shard_id =0 and --shard_id=19 for generate_dense_embeddings.py?  I mean if I set the  --num_shards = 2 and run --shard_id =0 and --shard_id=1 for generate_dense_embeddings.py then rerun this dense_retriever.py, then the below issue should be fixed? Thanks very much!

loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home1/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
Loading saved model state ...
Encoder vector_size=768
Reading all passages data from files: ['output/dpr_ctx.index_meta.dpr', 'output/dpr_ctx_0', 'output/dpr_ctx.index.dpr', 'output/dpr_ctx_19']
Reading file output/dpr_ctx.index_meta.dpr
Traceback (most recent call last):
  File "dense_retriever.py", line 284, in <module>
    main(args)
  File "dense_retriever.py", line 223, in main
    retriever.index.index_data(input_paths)
  File "/work/DPR/dpr/indexer/faiss_indexers.py", line 34, in index_data
    for i, item in enumerate(iterate_encoded_files(vector_files)):
  File "/work/DPR/dpr/indexer/faiss_indexers.py", line 190, in iterate_encoded_files
    db_id, doc_vector = doc
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by vlad-karpukhin** [comment]
Hello,
"Reading all passages data from files" - it lists the files which should be serialized vectors generated by generate_dense_embeddings, which are  'output/dpr_ctx_0' & 'output/dpr_ctx_19'
But the others - 'output/dpr_ctx.index_meta.dpr' & 'output/dpr_ctx.index.dpr' named like they are serialized dpr indexes.
So, they are the results of calling retriever.index.serialize(index_path). 
They have different formats and sure they cause an error since the code expects just a list of (db_id, doc_vector) tuples serialized in those files.
You need to exclude those from encoded_ctx_file glob expression if you want to build the index from scratch and don't use serialized one form some of you previous runs

**Comment by szhang42** [comment]
Hello Vladimir,

Thanks very much! This is very helpful. 

I have a following up question for this. While I made the above changes you mentioned in the last comment, I incurred the below problems. It says "unicodeDecodeerror". I used the below command to run the dense retriever.py. Is this unicodeDecodeerror due to the error from the dpr_ctx_0? Thanks again!

Total encoded queries tensor torch.Size([8757, 768])
index search time: 414.962713 sec.
Reading data from: output/dpr_ctx_0
Traceback (most recent call last):
  File "dense_retriever.py", line 284, in <module>
    main(args)
  File "dense_retriever.py", line 240, in main
    all_passages = load_passages(args.ctx_file)
  File "dense_retriever.py", line 132, in load_passages
    for row in reader:
  File "/opt/apps/intel19/python3/3.7.0/lib/python3.7/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Command: 
python3 dense_retriever.py \
  --model_file output/checkpoint/retriever/multiset/bert-base-encoder.cp \
  --ctx_file output/dpr_ctx_0 \
  --qa_file output/data/retriever/qas/nq-dev.csv \
  --encoded_ctx_file output/'dpr_ctx*' \
  --out_file output/dpr_retrieval/nq-dev.json \
  --n-docs 100 \
  --validation_workers 32 \
  --batch_size 64

**Comment by vlad-karpukhin** [comment]
If you check the description of --ctx_file parma, it will be:
"All passages file in the tsv format: id \\t passage_text \\t title"
So you set textual tsv formatted database of all passages to point to pickled embeddings.
Sure, there is a file read error.

--encoded_ctx_file - is a glob expression to files with pickled passage embeddings (i.e passage_id, vector)
--ctx_file - is a ling to the original 'database' of passages in textual format: passage_id, text, title
--qa_file - a file with textual questions and their answers

**Comment by szhang42** [comment]
Hello Vladimir,

Thanks very much! It is all clear now. Very much appreciate!
