### ISSUE TITLE
Training but not showing any GPU usage

### ISSUE THREAD

**Issue by zhenduow** [facebookresearch/DPR#54]
Hi, 

I use the following code to train on my dataset. 

`CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0,1,2,3 /usr/bin/python3.6 train_dense_encoder.py --encoder_model_type hf_ber
t --model_file checkpoint/retriever/multiset/bert-base-encoder.cp --pretrained_model_cfg bert-base-uncased --train_file ../data/DPR_question_retriever_
training --dev_file ../data/DPR_question_retriever_training --output_dir checkpoint/retriever/multiset`

But I cannot see any GPU usage (extremely low). Also the training seems stopping at epoch 1. What would be the problem? Thank you!

**Comment by vlad-karpukhin** [comment]
Hi Zhenduo,
There is not much I can do just based on the information above.
Can you provide at least the entire log for the run above?
Also, what is your torch and transformers versions?
We encountered some issues with their specific combinations and DPR in the past.

**Comment by zhenduow** [comment]
> Hi Zhenduo,
> There is not much I can do just based on the information above.
> Can you provide at least the entire log for the run above?
> Also, what is your torch and transformers versions?
> We encountered some issues with their specific combinations and DPR in the past.

Hi vlad-karpukhin,

My torch version is 1.4.0, my transformer version is 2.8.0. My CUDA verson is 10.1. This is my entire log.

Initialized host nanyuan as d.rank -1 on device=cuda, n_gpu=4, world size=1
16-bits training: False
 **************** CONFIGURATION ****************
adam_betas                     -->   (0.9, 0.999)
...
 **************** CONFIGURATION ****************
***** Initializing components for training *****
Reading saved model from checkpoint/retriever/multiset/bert-base-encoder.cp
model_state_dict keys odict_keys(['model_dict', 'optimizer_dict', 'scheduler_dict', 'offset', 'epoch', 'encoder_params'])
Overriding args parameter value from checkpoint state. Param = do_lower_case, value = True
Overriding args parameter value from checkpoint state. Param = pretrained_model_cfg, value = bert-base-uncased
Overriding args parameter value from checkpoint state. Param = encoder_model_type, value = hf_bert
Overriding args parameter value from checkpoint state. Param = sequence_length, value = 256
PyTorch version 1.4.0 available.
2020-08-29 08:22:58.415040: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: 
libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-08-29 08:22:58.415146: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dl
error: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-08-29 08:22:58.415156: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvi
dia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
TensorFlow version 2.1.0 available.
loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /home/zhenduow/.cache/torch/
transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517
Model config BertConfig {
...
}
loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin from cache at /home/zhenduow/.cache/torch/
transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /home/zhenduow/.cache/torch/
transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517
Model config BertConfig {
...
}
loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin from cache at /home/zhenduow/.cache/torch/transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/zhenduow/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
Loading checkpoint @ batch=0 and epoch=1
Loading saved model state ...
Reading file ../data/DPR_question_retriever_training
Aggregated data size: 7810
Total cleaned data size: 7810
  Total iterations per epoch=3905
 Total updates=7810
  Eval step = 3905
***** Training *****
***** Epoch 1 *****

and this is where it gets stuck.

**Comment by vlad-karpukhin** [comment]
you are running the retriever trining in the DP mode, but I used mostly DDP mode for that.
Have you tried DDP mode using pytorch launcher ?
"python -m torch.distributed.launch --nproc_per_node=4 ...."

**Comment by zhenduow** [comment]
Now it is working! Thank you!
