### ISSUE TITLE
requirements.txt file for the project

### ISSUE THREAD

**Issue by vaibhavad** [facebookresearch/DPR#55]
Hi,

Is it possible to add a reqiurements.txt file to this project, which contains all the library dependencies?

**Comment by yuchenlin** [comment]
same here. I found that the pre-trained checkpoints (hf) does not work with current latest huggingface. I used `pip install transformers==3.0.2` instead.

**Comment by vaibhavad** [comment]
> I found that the pre-trained checkpoints (hf) does not work with current latest huggingface. I used `pip install transformers==3.0.2` instead.

This was indeed the problem. Thanks @yuchenlin!

**Comment by vlad-karpukhin** [comment]
Hi,
DPR is supposed to work with the newest transformers lib
There have been some issue(warning level) with its newer version recently but was fixed here in the master branch.
If it still doesn't work we are to fix it.

**Comment by yuchenlin** [comment]
> Hi,
> DPR is supposed to work with the newest transformers lib
> There have been some issue(warning level) with its newer version recently but was fixed here in the master branch.
> If it still doesn't work we are to fix it.

I assume DPR now works with the newest hg transformers lib if we train a new model from the scratch. The issue we had was about loading the pre-trained hf checkpoints. When we tried to load it, it will say there was some mismatch in the file. That's why we changed the version to 3.0.2 and it works.

**Comment by vlad-karpukhin** [comment]
Hi Yuchen,
thanks for the info!
can you post here what was the issue specifically?
we certainly don't want to limit DPR to a specific HF version and need to make a fix or workaround.

I myself upgraded from 2.x to 3.0.2 once and had no issues with loading old checkpoints.

**Comment by yuchenlin** [comment]
Sure, I will post the bug report here later. To be clear, the bug was for the newest 3.1.0 version of HF, not the 3.0.2.

**Comment by vaibhavad** [comment]
The pre-trained checkpoints downloaded using [download_data.py](data/download_data.py) work with HF 3.0.2. They don't work with HF 3.1.0, you can find the error logs [here](https://github.com/facebookresearch/DPR/issues/58#issue-694265109)

I think just re-training using HF 3.1.0 and updating the checkpoints should solve the issue
