### ISSUE TITLE
BM25 baselines replication reported in the paper

### ISSUE THREAD

**Issue by NThakur20** [facebookresearch/DPR#57]
Hi @vlad-karpukhin ,

I wanted to replicate the BM25 retrieval results mentioned in Table 2 in the DPR paper. When I read footer 8 - 

> Lucene implementation. BM25 parameters b = 0.4 (document length normalization) and k1 = 0.9 (term frequency
scaling) are tuned using development sets

I, unfortunately, find nothing on reproducing the BM25 benchmarks within this repository and I wish to run the same BM25 benchmark for NQ and SQuAD datasets -- could you direct me if there is any open-sourced code available? Do you implement Anserini BM25 or something else (code reference if available would be really helpful)?

Kind Regards,
Nandan Thakur

**Comment by vlad-karpukhin** [comment]
Hi Nandan,
Bringing Lucene implementation to the project would be to add install Java as a dependency which we tried  to avoid.
We have a set of bash scripts and Java code but it is not in any shareable form unfortunately.
We just used title and our passages text as two separate document fields when indexing and used both fields when searching.

**Comment by NThakur20** [comment]
Thanks for the prompt reply, I understand the concerns for not adding it to the repository.

**Comment by sysu-zjw** [comment]
Hi, @vlad-karpukhin . Could you share the BM25 top5 retriever accuracy on NQ or the BM25 retrieval result? I am trying to build a BM25 baseline (top5/top10/top20/top100), but my BM25 scores is a bit different from yours. 
Appreciate it if you could offer some retrieval results from your BM25 version!
