### ISSUE TITLE
A question on hardware requirements to run retriever validation

### ISSUE THREAD

**Issue by AkariAsai** [facebookresearch/DPR#6]
Hi, thank you so much for open-sourcing DPR! I have a question about hardware requirements. 

I would like to run validation on the retrieval task and downloaded the checkpoints as well as generated vectors for NQ following the instruction in [this issue](https://github.com/facebookresearch/DPR/issues/3). Yet, when I was trying to run validation with [this command](https://github.com/facebookresearch/DPR#retriever-validation-against-the-entire-set-of-documents), the program was terminated due to Memory error during building index with `faiss_indexer` (related: https://github.com/facebookresearch/faiss/issues/180 )

```
Traceback (most recent call last):
  File "dense_retriever.py", line 285, in <module>
    main(args)
  File "dense_retriever.py", line 226, in main
    retriever.index_encoded_data(input_paths, buffer_size=index_buffer_sz)
  File "dense_retriever.py", line 94, in index_encoded_data
    self.index.index_data(buffer)
  File "/home/akari/projects/DPR/dpr/indexer/faiss_indexers.py", line 77, in index_data
    self.index.add(vectors)
  File "/home/akari/projects/DPR/dpr_env/lib/python3.6/site-packages/faiss/__init__.py", line 138, in replacement_add
    self.add_c(n, swig_ptr(x))
  File "/home/akari/projects/DPR/dpr_env/lib/python3.6/site-packages/faiss/swigfaiss.py", line 1454, in add
    return _swigfaiss.IndexFlat_add(self, n, x)
MemoryError: std::bad_alloc
```
Would you tell me how much memory our machine should have to run the validation? (I do not need to re-train the model right now).  My machine has 62GB of of RAM. If it takes more than that, are there any options to reduce RAM usage during indexing?

**Comment by vlad-karpukhin** [comment]
Hi Akari,
Unfortunately, 62 GB RAM is not enough even for simple "flat" index. Our wikipedia has 21 mln passages and given each vector's size 768x4 bytes this already gives ~ 60 GB.

**Comment by AkariAsai** [comment]
Hi Vladimir, thanks for your prompt response! Would you tell me rough estimation of the required RAM? We have some machines available and wonder which one is likely to have enough RAM (one has 125GB RAM in total).

**Comment by vlad-karpukhin** [comment]
This depends on OS memory consumption. Besides the index, the validation also reads all passages' string representations (i.e entire wikipedia text). This also takes ~ 25GB if I remember correctly. I'd say 120GB should be enough. 
Using HNSW index (suitable to fast inference but takes a lot of time to be indexed) requires even more memory (150gb index alone).
Unfortunately, DPR is quite demanding in terms of RAM amount and gpus for training (you should have at least 8x32 gb to be able to get results similar to ours)

**Comment by AkariAsai** [comment]
Then we'll try DPR on our machine with 120GB memory first. I'll close the issue now. Thank you so much for such a prompt and detailed response!
