### ISSUE TITLE
Can DPR be used for closed domain QA

### ISSUE THREAD

**Issue by dkamalakar** [facebookresearch/DPR#60]
I am curious if I can use DPR for closed domain QA once I have retriver trained ?

**Comment by vlad-karpukhin** [comment]
Hi,
Do you mean to use retriever as a reranker for a relatively small amount of passages per question?

**Comment by dkamalakar** [comment]
Yes

**Comment by vlad-karpukhin** [comment]
Yes, you can sure use DPR retriever model that as a reranker, but it might be not the best choice for closed domain settings.
You can sure get more high quality results if you train a separate reranker with full cross attention.
In fact, our reader model includes the reranker component already and may be a better choice for that.

**Comment by dkamalakar** [comment]
@vlad-karpukhin Thank you appreciate it
