### ISSUE TITLE
How is (ICT) Wikipedia Pre-training carried out in section 4.1 of paper?

### ISSUE THREAD

**Issue by NThakur20** [facebookresearch/DPR#61]
Hi @vlad-karpukhin ,

I understand the Wikipedia pre-processing method in Section 4.1 of the paper. However, I couldn't find a mention of how the model is trained from these 21,015,324 passages that are used for the pre-training of DPR models. Do you train using ICT i.e. break passage (100 words) into sentences and try to predict the context given the sentence? If yes, do you chose the sentence at random? I trained models choosing a sentence at random, but it leads to worse performances, so I was wondering where did I go wrong? 

If it's not pre-trained like ICT, could you explain how the pre-training of the model is done?

Kind Regards,
Nandan

**Comment by vlad-karpukhin** [comment]
Hi,
21,015,324 passages are used to mine hard negatives using bm25, 
it is the only way it participates in the training. We didn't use ICT, we just fine-tuned raw BERT/RoBerta.
Moreover, our experiments with ICT showed that it doesn't give any benefits vs fine-tuning on top of raw BERT/RoBerta models.

**Comment by NThakur20** [comment]
I see, Thank you @vlad-karpukhin for the explanation.

Yes, even I am encountering similar results with ICT unfortunately, it's not giving any benefits vs fine-tuning on top of raw BERT models.
