### ISSUE TITLE
reader inference infinite running with very high CPU utilization and memory

### ISSUE THREAD

**Issue by xixiaoyao** [facebookresearch/DPR#63]
I just following readme to do reader inference, run with following commands

```
export CUDA_VISIBLE_DEVICES=0
python train_reader.py \
  --prediction_results_file ./results.json \
  --eval_top_docs 10 20 40 50 80 100 \
  --dev_file test.0.pkl \
  --model_file hf_bert_base.cp \
  --log_batch_step 1 \
  --dev_batch_size 80 \
  --passages_per_question_predict 100 \
  --sequence_length 350
```

However, the process get stuck in this position for an hour 

![image](https://user-images.githubusercontent.com/24541791/94547691-3437ac80-0282-11eb-9805-48172fbb3b13.png)

And I find GPU utilization is 0, and CPU utilization and memory consuming is very horrible. 

![image](https://user-images.githubusercontent.com/24541791/94546746-e7070b00-0280-11eb-937f-c39957700fc8.png)

I did not modify any code. The env is

python == 3.7.7
CUDA == 10.1
torch == 1.6.0
transformers == 2.11.0

**Comment by xixiaoyao** [comment]
after about half an hour, I find it achieved the evaluation of ONE batch... There exists 8 GPUs in my environment and no-cuda has been set False. The speed also seems abnormal...

**Comment by vlad-karpukhin** [comment]
Hi,
That is really strange
Can you try to use 2 gpus at least and set batch size>2 ?

**Comment by vlad-karpukhin** [comment]
closing, no further details provided
