### ISSUE TITLE
Fine-tune using trained model on nq

### ISSUE THREAD

**Issue by Sharathmk99** [facebookresearch/DPR#66]
Hello,

Thank you amazing paper and also for open sourcing the code.
We tried to train retriever model using nq dataset, but we have only 1 GPU of 12GB. From issue #64 i understood we need more than one GPU to train the model. 
I was thinking if its possible to use already trained model using nq dataset and then fine-tune on my own dataset(which is much smaller)?
We were able to use DPR model using huggingface transformers, but didn't get any docs to fine-tune on my own dataset which is much smaller.

Thank you!

**Comment by vlad-karpukhin** [comment]
Hi,
Unfortunately, retriever training quality depends on effective batch size - when found that using <128 questions per batch degrades the model quality. We were able to fit that batch only using  8x32 GB GPUs.
For other datasets finetuning you can try to use smaller batch size.
We also tried to fine-tune this model for other datasets but the best fine-tuning schema is to jointly train NQ(and other Q&A datasets) with your custom dataset. This should provide the best results but will require large batch size.

**Comment by Sharathmk99** [comment]
Hi,
Oh ok. I'll try to figure out how to get 8x32GB GPUs. Any idea how much time it took for nq dataset to train?

**Comment by vlad-karpukhin** [comment]
It takes about a day for 128 batch size and NQ only train dataset to run for 40 epochs which was enough for our results

**Comment by Sharathmk99** [comment]
Thank you @vlad-karpukhin for your quick response.

**Comment by vlad-karpukhin** [comment]
Looks like we can close it now
