### ISSUE TITLE
pad_token_type_id or pad_token_id in BertTensorizer()

### ISSUE THREAD

**Issue by gengchenmai** [facebookresearch/DPR#72]
Hi, 

in BertTensorizer() class from` dpr/models/hf_models.py`, I see a function `get_pad_id(self)`, I believe here we should use `self.tokenizer.pad_token_id`, not `self.tokenizer.pad_token_type_id`. Althought they are both `0`, they have different semantics. Correct?

Gengchen

**Comment by vlad-karpukhin** [comment]
Hi Gengchen,
you are probably right.
As I remember I first used pad_token_id but it wasn't correct in HF, they probably fixed a while ago.

**Comment by gengchenmai** [comment]
My current HF tansformers version is 3.0.2. Both `self.tokenizer.pad_token_id` and `self.tokenizer.pad_token_type_id` return 0. But they have different semantics. This bug will not affect the current model. But I think it might affect in later version of transformers.

Best,
Gengchen
UC Santa Barbara
