### ISSUE TITLE
How long does BERT embedding the new query online 

### ISSUE THREAD

**Issue by MrRace** [facebookresearch/DPR#74]
The embeddings of all documents can do off-line , but in production environment, when a new query come, how long it will cost to get the query embedding？
Thanks a lot!

**Comment by vlad-karpukhin** [comment]
Hi, 
we haven't measured single query latency. It should be an equivalent of a single eval-only bert encoder forward pass.
Which is probably high anyway for production use and you would need some distilled model to reduce the latency.
