### ISSUE TITLE
More Top-k numbers

### ISSUE THREAD

**Issue by gangiswag** [facebookresearch/DPR#78]
Hi,

Thanks a lot for open-sourcing the code and sharing the data, trained models.

In the paper, only the top-20 and top-100 retrieval accuracy is reported. Would it be possible to also share the Top-1, Top-5 and Top-10 numbers too?

Preferably for the TriviaQA and WebQuestions datasets and numbers for the BM25 and DPR-single models should be enough.

We were able to get these numbers for NQ using the NQ trained retriever and index which are already available.

**Comment by vlad-karpukhin** [comment]
Hi,

here are the results for top for each k from 1 to 100:

TriviaQA, test set:
Single model:
0.531
0.615
0.659
0.685
0.704
0.716
0.729
0.739
0.747
0.754
0.759
0.763
0.767
0.772
0.775
0.778
0.782
0.784
0.786
0.788
0.79
0.793
0.795
0.797
0.799
0.802
0.803
0.805
0.807
0.808
0.809
0.811
0.811
0.813
0.814
0.815
0.816
0.817
0.818
0.819
0.82
0.821
0.822
0.822
0.823
0.824
0.825
0.825
0.826
0.827
0.828
0.829
0.829
0.83
0.83
0.831
0.832
0.832
0.832
0.833
0.833
0.834
0.834
0.835
0.835
0.835
0.836
0.836
0.837
0.838
0.838
0.838
0.839
0.839
0.839
0.84
0.841
0.841
0.842
0.842
0.843
0.843
0.843
0.843
0.844
0.844
0.844
0.844
0.844
0.845
0.846
0.846
0.846
0.846
0.846
0.847
0.847
0.848
0.848
0.848

WebQ Dev set:
Single model:

0.341
0.479
0.551
0.582
0.62
0.651
0.668
0.679
0.684
0.701
0.704
0.712
0.717
0.723
0.726
0.734
0.737
0.748
0.748
0.748
0.748
0.751
0.753
0.753
0.756
0.765
0.765
0.767
0.77
0.773
0.773
0.776
0.776
0.778
0.778
0.781
0.781
0.787
0.787
0.787
0.787
0.789
0.792
0.798
0.801
0.801
0.801
0.801
0.803
0.806
0.809
0.812
0.812
0.814
0.814
0.817
0.82
0.82
0.82
0.82
0.82
0.82
0.82
0.825
0.825
0.825
0.828
0.828
0.828
0.831
0.831
0.831
0.831
0.831
0.831
0.831
0.831
0.831
0.831
0.831
0.831
0.834
0.839
0.839
0.839
0.839
0.839
0.839
0.839
0.839
0.839
0.839
0.839
0.839
0.839
0.842
0.842
0.842
0.842
0.842

WebQ dev, Multi-set model:

0.424
0.507
0.565
0.596
0.618
0.64
0.654
0.67
0.684
0.687
0.695
0.698
0.704
0.72
0.726
0.731
0.731
0.74
0.745
0.751
0.756
0.759
0.762
0.767
0.77
0.773
0.773
0.778
0.778
0.778
0.778
0.778
0.781
0.787
0.787
0.787
0.792
0.801
0.801
0.801
0.801
0.803
0.803
0.806
0.806
0.814
0.814
0.817
0.817
0.817
0.82
0.823
0.823
0.825
0.825
0.825
0.825
0.825
0.831
0.831
0.834
0.834
0.834
0.834
0.837
0.837
0.839
0.839
0.845
0.845
0.845
0.848
0.848
0.848
0.85
0.85
0.85
0.85
0.85
0.85
0.85
0.853
0.853
0.853
0.853
0.856
0.856
0.856
0.856
0.856
0.856
0.856
0.856
0.856
0.856
0.856
0.859
0.861
0.861
0.861


Unfortunately, I can't find BM25 results as of now.

**Comment by gangiswag** [comment]
Thanks a lot for sharing the numbers. 
Please let us know if you are able to get the BM25 numbers.

Also can you share the Web Questions test set (single model) numbers too?

**Comment by vlad-karpukhin** [comment]
Hi,
here are results for WebQ test set dense model trained on WebQ only:


0.372
0.469
0.54
0.581
0.609
0.625
0.647
0.658
0.665
0.677
0.685
0.693
0.701
0.708
0.713
0.717
0.723
0.727
0.729
0.732
0.737
0.74
0.742
0.744
0.747
0.748
0.75
0.753
0.755
0.756
0.756
0.758
0.759
0.759
0.763
0.763
0.766
0.767
0.768
0.771
0.771
0.773
0.774
0.775
0.776
0.776
0.778
0.779
0.78
0.781
0.783
0.784
0.786
0.787
0.788
0.789
0.79
0.791
0.791
0.791
0.793
0.794
0.794
0.795
0.795
0.795
0.796
0.796
0.797
0.797
0.798
0.799
0.799
0.799
0.799
0.8
0.8
0.801
0.801
0.801
0.802
0.803
0.804
0.805
0.805
0.806
0.806
0.806
0.807
0.807
0.807
0.808
0.81
0.81
0.81
0.811
0.812
0.813
0.813
0.814

Sorry, I can't get bm25 numbers now.

**Comment by robinsongh381** [comment]
@vlad-karpukhin 
hello !

Your comment is not consistent with the Table2.
![image](https://user-images.githubusercontent.com/42966248/114553544-b3318700-9ca0-11eb-8624-45b9b5792d89.png)

The top-20 / 100 for Trivia QA test set is 79.4 and 85.0, respectively but your below comment suggests that the top-20/100 is 78.8 and 84.8, respectively. 

Which one is correct ?

`
TriviaQA, test set:
Single model:
0.531
0.615
0.659
0.685
0.704
0.716
0.729
0.739
0.747
0.754
0.759
0.763
0.767
0.772
0.775
0.778
0.782
0.784
0.786
0.788
0.79
0.793
0.795
0.797
0.799
0.802
0.803
0.805
0.807
0.808
0.809
0.811
0.811
0.813
0.814
0.815
0.816
0.817
0.818
0.819
0.82
0.821
0.822
0.822
0.823
0.824
0.825
0.825
0.826
0.827
0.828
0.829
0.829
0.83
0.83
0.831
0.832
0.832
0.832
0.833
0.833
0.834
0.834
0.835
0.835
0.835
0.836
0.836
0.837
0.838
0.838
0.838
0.839
0.839
0.839
0.84
0.841
0.841
0.842
0.842
0.843
0.843
0.843
0.843
0.844
0.844
0.844
0.844
0.844
0.845
0.846
0.846
0.846
0.846
0.846
0.847
0.847
0.848
0.848
0.848
`
