### ISSUE TITLE
Why don't we train the question encoder in BiEncoder when execute train_dense_encoder.py

### ISSUE THREAD

**Issue by bitxinyu** [facebookresearch/DPR#81]
Hello
Thanks a lot for open-sourcing the code.

I see this code in dpr/models/hf_models.py line 38.
`biencoder = BiEncoder(question_encoder, ctx_encoder, fix_ctx_encoder=fix_ctx_encoder)`
thus, fix_q_encoder is always False . Why don't we fine-tuning question encoder？

**Comment by vlad-karpukhin** [comment]
Hi,
fix_q_encoder=False means it is not fixed and thus fine-tuned.

**Comment by bitxinyu** [comment]
Thanks a lot, I think I just not find and realized the fix_q_encoder doesn't mean fine-tuning question encoder.
But I still don't understand what fix_encoder means. this code in class BiEncoder
```python
if fix_encoder:
    with torch.no_grad():
        sequence_output, pooled_output, hidden_states = sub_model(ids, segments, attn_mask)

    if sub_model.training:
         sequence_output.requires_grad_(requires_grad=True)
         pooled_output.requires_grad_(requires_grad=True)
else:
    sequence_output, pooled_output, hidden_states = sub_model(ids, segments, attn_mask)
```
when fix_encoder is True, first forward sub_model with no grad, then set sequence_output and pooled_output requires_grad().
I am confused about this code.

**Comment by vlad-karpukhin** [comment]
fix_encoder - it is an experimental feature. You don't need to use that in order to use our standard, described in the paper pipeline. You can't even enable it from cli without modifying the code.

**Comment by bitxinyu** [comment]
@vlad-karpukhin I see, Thanks.
