### ISSUE TITLE
unexpected result comparing to paper

### ISSUE THREAD

**Issue by swaggy-TN** [facebookresearch/DPR#86]
Hi,

I tested the reader using released checkpoint on the `nq dataset` and got EM scores as follows:
```
Aggregated data size: 3610
Total data size: 3610
n=10    EM 7.73
n=20    EM 7.26
n=40    EM 6.59
n=50    EM 6.40
n=80    EM 5.93
n=100   EM 5.87
```
They are significantly lower than those reported in the paper.

Here is the script I ran.

```bash
python ../train_reader.py \
        --prediction_results_file ../reader_inference/fb_results.json \
        --eval_top_docs 10 20 40 50 80 100 \
        --dev_file ../data/retriever_results/nq/single/test0.json \
        --model_file checkpoint/reader/nq-single/hf-bert-base.cp \
        --dev_batch_size 40 \
        --passages_per_question_predict 100 \
        --sequence_length 350 \
        --encoder_model_type hf_bert \
        --pretrained_model_cfg bert-base-uncased\

```

Plz help if somebody reproduced the results.

**Comment by vlad-karpukhin** [comment]
Hi, 
it is the first time I see such low numbers when evaluating our reader model.
I don't see any issues with the parameters you use.
Can you provide your full output log file?

**Comment by swaggy-TN** [comment]
Hi,

Thanks for replying. I restart the whole procedure and now my EM score is good. I think maybe it was the test dataset that caused such poor result.

**Comment by vlad-karpukhin** [comment]
great!
glad you found the reason.
