### ISSUE TITLE
Why validation accuracy is so low?

### ISSUE THREAD

**Issue by zsweet** [facebookresearch/DPR#89]
I train the model on the data which build on chinese reading comprehension data set such as CMRC2018. The validation log using `validate_nll` function is just 20%  while the final dev dataset accuracy can reach 90%+. Why do this happen？Is there some wrong with the code? below is the log picture:
![image](https://user-images.githubusercontent.com/28045074/102448280-c9ba2f80-406c-11eb-948e-94825c1ff3bb.png)

thanks for your reply! @vlad-karpukhin

**Comment by vlad-karpukhin** [comment]
Hi,
That seems strange, and I have no idea without additional information why it happens.
Can you provide more debugging details and how you created your dataset, how you mined hard negatives if any?

**Comment by zsweet** [comment]
thanks，I found that the problem of my data.
