### ISSUE TITLE
what should be the value for encoded_ctx_file argument when run dense_retriever.py

### ISSUE THREAD

**Issue by luomancs** [facebookresearch/DPR#90]
Hi, 
I have got 8 pkl file for the indexing of my documents. when I run dense_retriever.py, what should be the value for encoded_ctx_file? if I set the value be the d root folder then it reminds me that it is a directory, if I set the value be one of the file names, then it can not index all other files. 
in the readme, you said {encoded document files glob expression}, what does this mean? could you specify?

thank you

**Comment by vlad-karpukhin** [comment]
Hi,
that param should be a unix style pattern for ALL 8 files.
Generally, path to the folder and some common file prefix followed by *.
For example, if your generated files path is /home/user/projects/dpr/ and file pattern is wiki_encoded_{some number}.pkl.
You should set --encoded_ctx_file \"/home/user/projects/dpr/wiki_encoded_*.pkl\"
https://docs.python.org/3/library/glob.html

**Comment by luomancs** [comment]
works now, thank you.
