### ISSUE TITLE
doubt about the index of negative samples in the training of retriever

### ISSUE THREAD

**Issue by luomancs** [facebookresearch/DPR#92]
Hi, 

I took a look at the code in biencoder, I have doubts about lines137 -139. 

all_ctxs = [positive_ctx] + neg_ctxs + hard_neg_ctxs
hard_negatives_start_idx = 1
hard_negatives_end_idx = 1 + len(hard_neg_ctxs)

since in all_ctxs, you have three parts, and the last part is hard_neg_ctxs, so should the hard_negatives_start_idx be 1+ len(neg_ctxs)?

Thank you

**Comment by vlad-karpukhin** [comment]
Hi,
It indeed seems like a potential bug.
Those are the remnants of our experimental code and we don't use those hard_neg_ctx_indices as of now.
See a comment at:
https://github.com/facebookresearch/DPR/blob/27a8436b070861e2fff481e37244009b48c29c09/dpr/models/biencoder.py#L171
