### ISSUE TITLE
Gold passages info files for the SQuAD dataset

### ISSUE THREAD

**Issue by ikuyamada** [facebookresearch/DPR#93]
Hi,
Thank you for open-sourcing DPR!

I am working on reproducing the experimental results based on the SQuAD dataset.
If I correctly understand the paper (section 4.2: Selection of positive passages), we need *gold_passages_info* files to reproduce the SQuAD results, but it seems that these files are not available for this dataset.
Therefore, it would be appreciated if you could provide these files or brief instructions on how to create them.

Thank you very much in advance!

**Comment by okhat** [comment]
+1. Pumping this up as it would be greatly useful for us too!

**Comment by vlad-karpukhin** [comment]
hi,
sorry for a long reply.
I'm on vacations now and will provide SQuAD gold info files next week

**Comment by vlad-karpukhin** [comment]
Hello,
I've just checked our training logs for SQuAD and it appears we didn't use them for this dataset.
You can generate it from original SQuAD data, have a look at our NQ gold_passages_info files as an example.
You basically need just the provide the following attributes in json per question:
- question itself
- example_id - can be anything, no need to have unique ids.
- context - can be empty
- title - the most important, critical infor for our "is from gold page" heuristic. Must be provided.

**Comment by ikuyamada** [comment]
Hi,
Thank you very much for your detailed reply!
I failed to reproduce the retrieval results on SQuAD based on the code available in this repository, but I will investigate if there are any other issues.
