### ISSUE TITLE
Issues with the data

### ISSUE THREAD

**Issue by krishanudb** [facebookresearch/DPR#95]
Hi. 

I was looking at the data files you have processed and created.
In the retriever training files, for every question, there are three sets of texts:
positive_ctxs: which contain the answer
negative_ctxs: which do not contain the answer but are retrieved on the basis of BM25 scores
hard_negative_ctxs: do not contain the answer and have low BM25 score with question

My issue is that, while going through the positive_ctxs of some questions, I found several erroneous entries.
These entries do not talk about the answer, but are part of the positive_ctxs set for the question.

For e.g., in the first question of the nq-train.json file, the 2nd, 3rd texts of the positive_ctxs do not have the information to answer the question correctly. Still they are in the aforementioned set.

Is this an error or is this by design?
Thanks,
Krishanu.
Thanks.

**Comment by vlad-karpukhin** [comment]
Hi,
This is what we called semi-supervised setting when all passages(ctx+, ctx-, ctx_hard-) for question are collected from a large corpora using the simple answer presence check.
Sure answer span presence is not formally correct and you will have multiple false negatives and false positives among such data. We found that using such training data for NQ does affect the quality a bit (1-1.5 recall points) but our 'best' settings for NQ uses just the first ctx+ which is always the gold one.

**Comment by krishanudb** [comment]
Yes. I also guessed that the first ctx+ is the gold one. Thanks a lot for your reply. Sorts out several things for me.

**Comment by krishanudb** [comment]
Hi @vlad-karpukhin 
I had one more doubt. I am assuming the first ctx+, i.e. the gold passage is the same as the 'long answer' of the NQ dataset, right?
Thanks
Krishanu

**Comment by vlad-karpukhin** [comment]
Yes, the gold passage is taken from NQ's long answer candidates set with some straightforward logic to select the one that fits into 100 words chunks.

**Comment by vlad-karpukhin** [comment]
Actually, the first 'gold passage' is not exactly the one provided by NQ long answer spans. We used NQ's long answer passages as queries over our wikipedia's 100-words passages bm25 index to find their counterparts (otherwise we faced an issue that the model just learns to select NQ passages vs our wikipedia passages because of some formatting bias we were not able to figure out quickly).

**Comment by krishanudb** [comment]
Okay.. Got it.. Thanks a lot for replying so fast. btw I found your work very good, intuitive, and comprehensive. 
All the best,
Krishanu.
