### ISSUE TITLE
Multiset Trained Passage Embeddings

### ISSUE THREAD

**Issue by krishanudb** [facebookresearch/DPR#98]
Hi, 
Thanks for providing the precomputed embeddings of the Wikipedia passages using the encoder model trained on NQ.

"data.retriever_results.nq.single.wikipedia_passages"

Will it be possible to provide the precomputed embeddings of all Wikipedia passages using the multiset trained encoder?

Thanks

**Comment by vlad-karpukhin** [comment]
Hi @krishanudb ,
The NQ only model we provided and wikipedia embeddings for it are somewhat better reported in the paper, but this is not the case for the multiset model. 
I don't have the multi-set version in the current DPR format right now.

BTW, I plan to make a major DPR release soon with a lot of upgrades including the new set of models (including the multiset) which work much better than the current ones.

**Comment by krishanudb** [comment]
Great. Will be waiting for the release.
Thanks.

**Comment by krishanudb** [comment]
@vlad-karpukhin 
I just saw that DPR encoders models as well as reader models are available in Huggingface Transformers library.
However, I wasn't able to find out which models they were? Are those the multiset models or the NQ trained models?
Also, are the models found there are the ones here identical?
Thanks,
Krishanu.

**Comment by vlad-karpukhin** [comment]
Hi @krishanudb ,
The models in HF and ours should be identical - we provided them with the same checkpoints like in this repo. No sure if they provide NQ only or also multi-sets, you'll need to read that from their documentation.

**Comment by krishanudb** [comment]
Okay. Thanks a ton..
